
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: builtin_conditions.c
// Test C built-in conditions  (//!!except any left undefined)

// Basic usage of bool values in conditional jumps, but amenable to many model optimising techniques.
// These tests combine comparisons and various commonplace usage patterns.
//   cnv : (implicit) convert condition (typically same as ? 1 : 0)
//   cpl : (implicit) convert complemented condition
//   dir : direct condition ? 1 : 0
//   inv : invert condition ? 0 : 1
//   sel : conditional select between two values
//   jmp : same but constrained to use jumps (all of the above will be jumps unless optimised to intrinsics)
//   cad : select on logical and (2nd comparison)
//   cor : select on logical or  (2nd comparison)
//   lad : select on logical and (with load)
//   lor : select on logical or  (with load)
//   sad : select on logical and with side-effect (must not be speculated)
//   sor : select on logical or  with side-effect (must not be speculated)
// Depending on the model, these tests may all generate similar jump-based code or be quite distinctive.

// Note for volume reasons only testing the combinatorial diagonal with same input and output types.

extern "C" {

int ga;
volatile int gv;

//-- signed char

signed char bicnd___schar_barg_cnv(bool b) { return b; }
signed char bicnd___schar_barg_cpl(bool b) { return !b; }
signed char bicnd___schar_barg_dir(bool b) { return b ? 1 : 0; }
signed char bicnd___schar_barg_inv(bool b) { return b ? 0 : 1; }
signed char bicnd___schar_barg_sel(bool b, signed char v, signed char w) { return b ? v : w; }
signed char bicnd___schar_barg_jmp(bool b, signed char v, signed char w) { return b chess_keep_if ? v : w; }

signed char bicnd___schar_barg_cad(bool c, bool b, signed char v, signed char w) { return c && b ? v : w; }
signed char bicnd___schar_barg_cor(bool c, bool b, signed char v, signed char w) { return c || b ? v : w; }
signed char bicnd___schar_barg_lad(bool b, signed char v, signed char w) { return b && ga ? v : w; }
signed char bicnd___schar_barg_lor(bool b, signed char v, signed char w) { return b || ga ? v : w; }
signed char bicnd___schar_barg_sad(bool b, signed char v, signed char w) { return b && gv ? v : w; }
signed char bicnd___schar_barg_sor(bool b, signed char v, signed char w) { return b || gv ? v : w; }

//-- unsigned char

unsigned char bicnd___uchar_barg_cnv(bool b) { return b; }
unsigned char bicnd___uchar_barg_cpl(bool b) { return !b; }
unsigned char bicnd___uchar_barg_dir(bool b) { return b ? 1 : 0; }
unsigned char bicnd___uchar_barg_inv(bool b) { return b ? 0 : 1; }
unsigned char bicnd___uchar_barg_sel(bool b, unsigned char v, unsigned char w) { return b ? v : w; }
unsigned char bicnd___uchar_barg_jmp(bool b, unsigned char v, unsigned char w) { return b chess_keep_if ? v : w; }

unsigned char bicnd___uchar_barg_cad(bool c, bool b, unsigned char v, unsigned char w) { return c && b ? v : w; }
unsigned char bicnd___uchar_barg_cor(bool c, bool b, unsigned char v, unsigned char w) { return c || b ? v : w; }
unsigned char bicnd___uchar_barg_lad(bool b, unsigned char v, unsigned char w) { return b && ga ? v : w; }
unsigned char bicnd___uchar_barg_lor(bool b, unsigned char v, unsigned char w) { return b || ga ? v : w; }
unsigned char bicnd___uchar_barg_sad(bool b, unsigned char v, unsigned char w) { return b && gv ? v : w; }
unsigned char bicnd___uchar_barg_sor(bool b, unsigned char v, unsigned char w) { return b || gv ? v : w; }

//-- short

short bicnd___sshort_barg_cnv(bool b) { return b; }
short bicnd___sshort_barg_cpl(bool b) { return !b; }
short bicnd___sshort_barg_dir(bool b) { return b ? 1 : 0; }
short bicnd___sshort_barg_inv(bool b) { return b ? 0 : 1; }
short bicnd___sshort_barg_sel(bool b, short v, short w) { return b ? v : w; }
short bicnd___sshort_barg_jmp(bool b, short v, short w) { return b chess_keep_if ? v : w; }

short bicnd___sshort_barg_cad(bool c, bool b, short v, short w) { return c && b ? v : w; }
short bicnd___sshort_barg_cor(bool c, bool b, short v, short w) { return c || b ? v : w; }
short bicnd___sshort_barg_lad(bool b, short v, short w) { return b && ga ? v : w; }
short bicnd___sshort_barg_lor(bool b, short v, short w) { return b || ga ? v : w; }
short bicnd___sshort_barg_sad(bool b, short v, short w) { return b && gv ? v : w; }
short bicnd___sshort_barg_sor(bool b, short v, short w) { return b || gv ? v : w; }

//-- unsigned short

unsigned short bicnd___ushort_barg_cnv(bool b) { return b; }
unsigned short bicnd___ushort_barg_cpl(bool b) { return !b; }
unsigned short bicnd___ushort_barg_dir(bool b) { return b ? 1 : 0; }
unsigned short bicnd___ushort_barg_inv(bool b) { return b ? 0 : 1; }
unsigned short bicnd___ushort_barg_sel(bool b, unsigned short v, unsigned short w) { return b ? v : w; }
unsigned short bicnd___ushort_barg_jmp(bool b, unsigned short v, unsigned short w) { return b chess_keep_if ? v : w; }

unsigned short bicnd___ushort_barg_cad(bool c, bool b, unsigned short v, unsigned short w) { return c && b ? v : w; }
unsigned short bicnd___ushort_barg_cor(bool c, bool b, unsigned short v, unsigned short w) { return c || b ? v : w; }
unsigned short bicnd___ushort_barg_lad(bool b, unsigned short v, unsigned short w) { return b && ga ? v : w; }
unsigned short bicnd___ushort_barg_lor(bool b, unsigned short v, unsigned short w) { return b || ga ? v : w; }
unsigned short bicnd___ushort_barg_sad(bool b, unsigned short v, unsigned short w) { return b && gv ? v : w; }
unsigned short bicnd___ushort_barg_sor(bool b, unsigned short v, unsigned short w) { return b || gv ? v : w; }

//-- int

int bicnd___sint_barg_cnv(bool b) { return b; }
int bicnd___sint_barg_cpl(bool b) { return !b; }
int bicnd___sint_barg_dir(bool b) { return b ? 1 : 0; }
int bicnd___sint_barg_inv(bool b) { return b ? 0 : 1; }
int bicnd___sint_barg_sel(bool b, int v, int w) { return b ? v : w; }
int bicnd___sint_barg_jmp(bool b, int v, int w) { return b chess_keep_if ? v : w; }

int bicnd___sint_barg_cad(bool c, bool b, int v, int w) { return c && b ? v : w; }
int bicnd___sint_barg_cor(bool c, bool b, int v, int w) { return c || b ? v : w; }
int bicnd___sint_barg_lad(bool b, int v, int w) { return b && ga ? v : w; }
int bicnd___sint_barg_lor(bool b, int v, int w) { return b || ga ? v : w; }
int bicnd___sint_barg_sad(bool b, int v, int w) { return b && gv ? v : w; }
int bicnd___sint_barg_sor(bool b, int v, int w) { return b || gv ? v : w; }

int bicnd___sint__lt_cnv(int a, int b) { return a < b; }
int bicnd___sint__lt_cpl(int a, int b) { return !(a < b); }
int bicnd___sint__lt_dir(int a, int b) { return a < b ? 1 : 0; }
int bicnd___sint__lt_inv(int a, int b) { return a < b ? 0 : 1; }
int bicnd___sint__lt_sel(int a, int b, int v, int w) { return a < b ? v : w; }
int bicnd___sint__lt_jmp(int a, int b, int v, int w) { return a < b chess_keep_if ? v : w; }

int bicnd___sint__lt_cad(bool c, int a, int b, int v, int w) { return c && a < b ? v : w; }
int bicnd___sint__lt_cor(bool c, int a, int b, int v, int w) { return c || a < b ? v : w; }
int bicnd___sint__lt_lad(int a, int b, int v, int w) { return a < b && ga ? v : w; }
int bicnd___sint__lt_lor(int a, int b, int v, int w) { return a < b || ga ? v : w; }
int bicnd___sint__lt_sad(int a, int b, int v, int w) { return a < b && gv ? v : w; }
int bicnd___sint__lt_sor(int a, int b, int v, int w) { return a < b || gv ? v : w; }

int bicnd___sint__gt_cnv(int a, int b) { return a > b; }
int bicnd___sint__gt_cpl(int a, int b) { return !(a > b); }
int bicnd___sint__gt_dir(int a, int b) { return a > b ? 1 : 0; }
int bicnd___sint__gt_inv(int a, int b) { return a > b ? 0 : 1; }
int bicnd___sint__gt_sel(int a, int b, int v, int w) { return a > b ? v : w; }
int bicnd___sint__gt_jmp(int a, int b, int v, int w) { return a > b chess_keep_if ? v : w; }

int bicnd___sint__gt_cad(bool c, int a, int b, int v, int w) { return c && a > b ? v : w; }
int bicnd___sint__gt_cor(bool c, int a, int b, int v, int w) { return c || a > b ? v : w; }
int bicnd___sint__gt_lad(int a, int b, int v, int w) { return a > b && ga ? v : w; }
int bicnd___sint__gt_lor(int a, int b, int v, int w) { return a > b || ga ? v : w; }
int bicnd___sint__gt_sad(int a, int b, int v, int w) { return a > b && gv ? v : w; }
int bicnd___sint__gt_sor(int a, int b, int v, int w) { return a > b || gv ? v : w; }

int bicnd___sint__le_cnv(int a, int b) { return a <= b; }
int bicnd___sint__le_cpl(int a, int b) { return !(a <= b); }
int bicnd___sint__le_dir(int a, int b) { return a <= b ? 1 : 0; }
int bicnd___sint__le_inv(int a, int b) { return a <= b ? 0 : 1; }
int bicnd___sint__le_sel(int a, int b, int v, int w) { return a <= b ? v : w; }
int bicnd___sint__le_jmp(int a, int b, int v, int w) { return a <= b chess_keep_if ? v : w; }

int bicnd___sint__le_cad(bool c, int a, int b, int v, int w) { return c && a <= b ? v : w; }
int bicnd___sint__le_cor(bool c, int a, int b, int v, int w) { return c || a <= b ? v : w; }
int bicnd___sint__le_lad(int a, int b, int v, int w) { return a <= b && ga ? v : w; }
int bicnd___sint__le_lor(int a, int b, int v, int w) { return a <= b || ga ? v : w; }
int bicnd___sint__le_sad(int a, int b, int v, int w) { return a <= b && gv ? v : w; }
int bicnd___sint__le_sor(int a, int b, int v, int w) { return a <= b || gv ? v : w; }

int bicnd___sint__ge_cnv(int a, int b) { return a >= b; }
int bicnd___sint__ge_cpl(int a, int b) { return !(a >= b); }
int bicnd___sint__ge_dir(int a, int b) { return a >= b ? 1 : 0; }
int bicnd___sint__ge_inv(int a, int b) { return a >= b ? 0 : 1; }
int bicnd___sint__ge_sel(int a, int b, int v, int w) { return a >= b ? v : w; }
int bicnd___sint__ge_jmp(int a, int b, int v, int w) { return a >= b chess_keep_if ? v : w; }

int bicnd___sint__ge_cad(bool c, int a, int b, int v, int w) { return c && a >= b ? v : w; }
int bicnd___sint__ge_cor(bool c, int a, int b, int v, int w) { return c || a >= b ? v : w; }
int bicnd___sint__ge_lad(int a, int b, int v, int w) { return a >= b && ga ? v : w; }
int bicnd___sint__ge_lor(int a, int b, int v, int w) { return a >= b || ga ? v : w; }
int bicnd___sint__ge_sad(int a, int b, int v, int w) { return a >= b && gv ? v : w; }
int bicnd___sint__ge_sor(int a, int b, int v, int w) { return a >= b || gv ? v : w; }

int bicnd___sint__eq_cnv(int a, int b) { return a == b; }
int bicnd___sint__eq_cpl(int a, int b) { return !(a == b); }
int bicnd___sint__eq_dir(int a, int b) { return a == b ? 1 : 0; }
int bicnd___sint__eq_inv(int a, int b) { return a == b ? 0 : 1; }
int bicnd___sint__eq_sel(int a, int b, int v, int w) { return a == b ? v : w; }
int bicnd___sint__eq_jmp(int a, int b, int v, int w) { return a == b chess_keep_if ? v : w; }

int bicnd___sint__eq_cad(bool c, int a, int b, int v, int w) { return c && a == b ? v : w; }
int bicnd___sint__eq_cor(bool c, int a, int b, int v, int w) { return c || a == b ? v : w; }
int bicnd___sint__eq_lad(int a, int b, int v, int w) { return a == b && ga ? v : w; }
int bicnd___sint__eq_lor(int a, int b, int v, int w) { return a == b || ga ? v : w; }
int bicnd___sint__eq_sad(int a, int b, int v, int w) { return a == b && gv ? v : w; }
int bicnd___sint__eq_sor(int a, int b, int v, int w) { return a == b || gv ? v : w; }

int bicnd___sint__ne_cnv(int a, int b) { return a != b; }
int bicnd___sint__ne_cpl(int a, int b) { return !(a != b); }
int bicnd___sint__ne_dir(int a, int b) { return a != b ? 1 : 0; }
int bicnd___sint__ne_inv(int a, int b) { return a != b ? 0 : 1; }
int bicnd___sint__ne_sel(int a, int b, int v, int w) { return a != b ? v : w; }
int bicnd___sint__ne_jmp(int a, int b, int v, int w) { return a != b chess_keep_if ? v : w; }

int bicnd___sint__ne_cad(bool c, int a, int b, int v, int w) { return c && a != b ? v : w; }
int bicnd___sint__ne_cor(bool c, int a, int b, int v, int w) { return c || a != b ? v : w; }
int bicnd___sint__ne_lad(int a, int b, int v, int w) { return a != b && ga ? v : w; }
int bicnd___sint__ne_lor(int a, int b, int v, int w) { return a != b || ga ? v : w; }
int bicnd___sint__ne_sad(int a, int b, int v, int w) { return a != b && gv ? v : w; }
int bicnd___sint__ne_sor(int a, int b, int v, int w) { return a != b || gv ? v : w; }

//-- unsigned

unsigned bicnd___uint_barg_cnv(bool b) { return b; }
unsigned bicnd___uint_barg_cpl(bool b) { return !b; }
unsigned bicnd___uint_barg_dir(bool b) { return b ? 1 : 0; }
unsigned bicnd___uint_barg_inv(bool b) { return b ? 0 : 1; }
unsigned bicnd___uint_barg_sel(bool b, unsigned v, unsigned w) { return b ? v : w; }
unsigned bicnd___uint_barg_jmp(bool b, unsigned v, unsigned w) { return b chess_keep_if ? v : w; }

unsigned bicnd___uint_barg_cad(bool c, bool b, unsigned v, unsigned w) { return c && b ? v : w; }
unsigned bicnd___uint_barg_cor(bool c, bool b, unsigned v, unsigned w) { return c || b ? v : w; }
unsigned bicnd___uint_barg_lad(bool b, unsigned v, unsigned w) { return b && ga ? v : w; }
unsigned bicnd___uint_barg_lor(bool b, unsigned v, unsigned w) { return b || ga ? v : w; }
unsigned bicnd___uint_barg_sad(bool b, unsigned v, unsigned w) { return b && gv ? v : w; }
unsigned bicnd___uint_barg_sor(bool b, unsigned v, unsigned w) { return b || gv ? v : w; }

unsigned bicnd___uint__lt_cnv(unsigned a, unsigned b) { return a < b; }
unsigned bicnd___uint__lt_cpl(unsigned a, unsigned b) { return !(a < b); }
unsigned bicnd___uint__lt_dir(unsigned a, unsigned b) { return a < b ? 1 : 0; }
unsigned bicnd___uint__lt_inv(unsigned a, unsigned b) { return a < b ? 0 : 1; }
unsigned bicnd___uint__lt_sel(unsigned a, unsigned b, unsigned v, unsigned w) { return a < b ? v : w; }
unsigned bicnd___uint__lt_jmp(unsigned a, unsigned b, unsigned v, unsigned w) { return a < b chess_keep_if ? v : w; }

unsigned bicnd___uint__lt_cad(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c && a < b ? v : w; }
unsigned bicnd___uint__lt_cor(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c || a < b ? v : w; }
unsigned bicnd___uint__lt_lad(unsigned a, unsigned b, unsigned v, unsigned w) { return a < b && ga ? v : w; }
unsigned bicnd___uint__lt_lor(unsigned a, unsigned b, unsigned v, unsigned w) { return a < b || ga ? v : w; }
unsigned bicnd___uint__lt_sad(unsigned a, unsigned b, unsigned v, unsigned w) { return a < b && gv ? v : w; }
unsigned bicnd___uint__lt_sor(unsigned a, unsigned b, unsigned v, unsigned w) { return a < b || gv ? v : w; }

unsigned bicnd___uint__gt_cnv(unsigned a, unsigned b) { return a > b; }
unsigned bicnd___uint__gt_cpl(unsigned a, unsigned b) { return !(a > b); }
unsigned bicnd___uint__gt_dir(unsigned a, unsigned b) { return a > b ? 1 : 0; }
unsigned bicnd___uint__gt_inv(unsigned a, unsigned b) { return a > b ? 0 : 1; }
unsigned bicnd___uint__gt_sel(unsigned a, unsigned b, unsigned v, unsigned w) { return a > b ? v : w; }
unsigned bicnd___uint__gt_jmp(unsigned a, unsigned b, unsigned v, unsigned w) { return a > b chess_keep_if ? v : w; }

unsigned bicnd___uint__gt_cad(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c && a > b ? v : w; }
unsigned bicnd___uint__gt_cor(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c || a > b ? v : w; }
unsigned bicnd___uint__gt_lad(unsigned a, unsigned b, unsigned v, unsigned w) { return a > b && ga ? v : w; }
unsigned bicnd___uint__gt_lor(unsigned a, unsigned b, unsigned v, unsigned w) { return a > b || ga ? v : w; }
unsigned bicnd___uint__gt_sad(unsigned a, unsigned b, unsigned v, unsigned w) { return a > b && gv ? v : w; }
unsigned bicnd___uint__gt_sor(unsigned a, unsigned b, unsigned v, unsigned w) { return a > b || gv ? v : w; }

unsigned bicnd___uint__le_cnv(unsigned a, unsigned b) { return a <= b; }
unsigned bicnd___uint__le_cpl(unsigned a, unsigned b) { return !(a <= b); }
unsigned bicnd___uint__le_dir(unsigned a, unsigned b) { return a <= b ? 1 : 0; }
unsigned bicnd___uint__le_inv(unsigned a, unsigned b) { return a <= b ? 0 : 1; }
unsigned bicnd___uint__le_sel(unsigned a, unsigned b, unsigned v, unsigned w) { return a <= b ? v : w; }
unsigned bicnd___uint__le_jmp(unsigned a, unsigned b, unsigned v, unsigned w) { return a <= b chess_keep_if ? v : w; }

unsigned bicnd___uint__le_cad(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c && a <= b ? v : w; }
unsigned bicnd___uint__le_cor(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c || a <= b ? v : w; }
unsigned bicnd___uint__le_lad(unsigned a, unsigned b, unsigned v, unsigned w) { return a <= b && ga ? v : w; }
unsigned bicnd___uint__le_lor(unsigned a, unsigned b, unsigned v, unsigned w) { return a <= b || ga ? v : w; }
unsigned bicnd___uint__le_sad(unsigned a, unsigned b, unsigned v, unsigned w) { return a <= b && gv ? v : w; }
unsigned bicnd___uint__le_sor(unsigned a, unsigned b, unsigned v, unsigned w) { return a <= b || gv ? v : w; }

unsigned bicnd___uint__ge_cnv(unsigned a, unsigned b) { return a >= b; }
unsigned bicnd___uint__ge_cpl(unsigned a, unsigned b) { return !(a >= b); }
unsigned bicnd___uint__ge_dir(unsigned a, unsigned b) { return a >= b ? 1 : 0; }
unsigned bicnd___uint__ge_inv(unsigned a, unsigned b) { return a >= b ? 0 : 1; }
unsigned bicnd___uint__ge_sel(unsigned a, unsigned b, unsigned v, unsigned w) { return a >= b ? v : w; }
unsigned bicnd___uint__ge_jmp(unsigned a, unsigned b, unsigned v, unsigned w) { return a >= b chess_keep_if ? v : w; }

unsigned bicnd___uint__ge_cad(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c && a >= b ? v : w; }
unsigned bicnd___uint__ge_cor(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c || a >= b ? v : w; }
unsigned bicnd___uint__ge_lad(unsigned a, unsigned b, unsigned v, unsigned w) { return a >= b && ga ? v : w; }
unsigned bicnd___uint__ge_lor(unsigned a, unsigned b, unsigned v, unsigned w) { return a >= b || ga ? v : w; }
unsigned bicnd___uint__ge_sad(unsigned a, unsigned b, unsigned v, unsigned w) { return a >= b && gv ? v : w; }
unsigned bicnd___uint__ge_sor(unsigned a, unsigned b, unsigned v, unsigned w) { return a >= b || gv ? v : w; }

unsigned bicnd___uint__eq_cnv(unsigned a, unsigned b) { return a == b; }
unsigned bicnd___uint__eq_cpl(unsigned a, unsigned b) { return !(a == b); }
unsigned bicnd___uint__eq_dir(unsigned a, unsigned b) { return a == b ? 1 : 0; }
unsigned bicnd___uint__eq_inv(unsigned a, unsigned b) { return a == b ? 0 : 1; }
unsigned bicnd___uint__eq_sel(unsigned a, unsigned b, unsigned v, unsigned w) { return a == b ? v : w; }
unsigned bicnd___uint__eq_jmp(unsigned a, unsigned b, unsigned v, unsigned w) { return a == b chess_keep_if ? v : w; }

unsigned bicnd___uint__eq_cad(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c && a == b ? v : w; }
unsigned bicnd___uint__eq_cor(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c || a == b ? v : w; }
unsigned bicnd___uint__eq_lad(unsigned a, unsigned b, unsigned v, unsigned w) { return a == b && ga ? v : w; }
unsigned bicnd___uint__eq_lor(unsigned a, unsigned b, unsigned v, unsigned w) { return a == b || ga ? v : w; }
unsigned bicnd___uint__eq_sad(unsigned a, unsigned b, unsigned v, unsigned w) { return a == b && gv ? v : w; }
unsigned bicnd___uint__eq_sor(unsigned a, unsigned b, unsigned v, unsigned w) { return a == b || gv ? v : w; }

unsigned bicnd___uint__ne_cnv(unsigned a, unsigned b) { return a != b; }
unsigned bicnd___uint__ne_cpl(unsigned a, unsigned b) { return !(a != b); }
unsigned bicnd___uint__ne_dir(unsigned a, unsigned b) { return a != b ? 1 : 0; }
unsigned bicnd___uint__ne_inv(unsigned a, unsigned b) { return a != b ? 0 : 1; }
unsigned bicnd___uint__ne_sel(unsigned a, unsigned b, unsigned v, unsigned w) { return a != b ? v : w; }
unsigned bicnd___uint__ne_jmp(unsigned a, unsigned b, unsigned v, unsigned w) { return a != b chess_keep_if ? v : w; }

unsigned bicnd___uint__ne_cad(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c && a != b ? v : w; }
unsigned bicnd___uint__ne_cor(bool c, unsigned a, unsigned b, unsigned v, unsigned w) { return c || a != b ? v : w; }
unsigned bicnd___uint__ne_lad(unsigned a, unsigned b, unsigned v, unsigned w) { return a != b && ga ? v : w; }
unsigned bicnd___uint__ne_lor(unsigned a, unsigned b, unsigned v, unsigned w) { return a != b || ga ? v : w; }
unsigned bicnd___uint__ne_sad(unsigned a, unsigned b, unsigned v, unsigned w) { return a != b && gv ? v : w; }
unsigned bicnd___uint__ne_sor(unsigned a, unsigned b, unsigned v, unsigned w) { return a != b || gv ? v : w; }

//-- long long

long long bicnd___slonglong_barg_cnv(bool b) { return b; }
long long bicnd___slonglong_barg_cpl(bool b) { return !b; }
long long bicnd___slonglong_barg_dir(bool b) { return b ? 1 : 0; }
long long bicnd___slonglong_barg_inv(bool b) { return b ? 0 : 1; }
long long bicnd___slonglong_barg_sel(bool b, long long v, long long w) { return b ? v : w; }
long long bicnd___slonglong_barg_jmp(bool b, long long v, long long w) { return b chess_keep_if ? v : w; }

long long bicnd___slonglong_barg_cad(bool c, bool b, long long v, long long w) { return c && b ? v : w; }
long long bicnd___slonglong_barg_cor(bool c, bool b, long long v, long long w) { return c || b ? v : w; }
long long bicnd___slonglong_barg_lad(bool b, long long v, long long w) { return b && ga ? v : w; }
long long bicnd___slonglong_barg_lor(bool b, long long v, long long w) { return b || ga ? v : w; }
long long bicnd___slonglong_barg_sad(bool b, long long v, long long w) { return b && gv ? v : w; }
long long bicnd___slonglong_barg_sor(bool b, long long v, long long w) { return b || gv ? v : w; }

long long bicnd___slonglong__lt_cnv(long long a, long long b) { return a < b; }
long long bicnd___slonglong__lt_cpl(long long a, long long b) { return !(a < b); }
long long bicnd___slonglong__lt_dir(long long a, long long b) { return a < b ? 1 : 0; }
long long bicnd___slonglong__lt_inv(long long a, long long b) { return a < b ? 0 : 1; }
long long bicnd___slonglong__lt_sel(long long a, long long b, long long v, long long w) { return a < b ? v : w; }
long long bicnd___slonglong__lt_jmp(long long a, long long b, long long v, long long w) { return a < b chess_keep_if ? v : w; }

long long bicnd___slonglong__lt_cad(bool c, long long a, long long b, long long v, long long w) { return c && a < b ? v : w; }
long long bicnd___slonglong__lt_cor(bool c, long long a, long long b, long long v, long long w) { return c || a < b ? v : w; }
long long bicnd___slonglong__lt_lad(long long a, long long b, long long v, long long w) { return a < b && ga ? v : w; }
long long bicnd___slonglong__lt_lor(long long a, long long b, long long v, long long w) { return a < b || ga ? v : w; }
long long bicnd___slonglong__lt_sad(long long a, long long b, long long v, long long w) { return a < b && gv ? v : w; }
long long bicnd___slonglong__lt_sor(long long a, long long b, long long v, long long w) { return a < b || gv ? v : w; }

long long bicnd___slonglong__gt_cnv(long long a, long long b) { return a > b; }
long long bicnd___slonglong__gt_cpl(long long a, long long b) { return !(a > b); }
long long bicnd___slonglong__gt_dir(long long a, long long b) { return a > b ? 1 : 0; }
long long bicnd___slonglong__gt_inv(long long a, long long b) { return a > b ? 0 : 1; }
long long bicnd___slonglong__gt_sel(long long a, long long b, long long v, long long w) { return a > b ? v : w; }
long long bicnd___slonglong__gt_jmp(long long a, long long b, long long v, long long w) { return a > b chess_keep_if ? v : w; }

long long bicnd___slonglong__gt_cad(bool c, long long a, long long b, long long v, long long w) { return c && a > b ? v : w; }
long long bicnd___slonglong__gt_cor(bool c, long long a, long long b, long long v, long long w) { return c || a > b ? v : w; }
long long bicnd___slonglong__gt_lad(long long a, long long b, long long v, long long w) { return a > b && ga ? v : w; }
long long bicnd___slonglong__gt_lor(long long a, long long b, long long v, long long w) { return a > b || ga ? v : w; }
long long bicnd___slonglong__gt_sad(long long a, long long b, long long v, long long w) { return a > b && gv ? v : w; }
long long bicnd___slonglong__gt_sor(long long a, long long b, long long v, long long w) { return a > b || gv ? v : w; }

long long bicnd___slonglong__le_cnv(long long a, long long b) { return a <= b; }
long long bicnd___slonglong__le_cpl(long long a, long long b) { return !(a <= b); }
long long bicnd___slonglong__le_dir(long long a, long long b) { return a <= b ? 1 : 0; }
long long bicnd___slonglong__le_inv(long long a, long long b) { return a <= b ? 0 : 1; }
long long bicnd___slonglong__le_sel(long long a, long long b, long long v, long long w) { return a <= b ? v : w; }
long long bicnd___slonglong__le_jmp(long long a, long long b, long long v, long long w) { return a <= b chess_keep_if ? v : w; }

long long bicnd___slonglong__le_cad(bool c, long long a, long long b, long long v, long long w) { return c && a <= b ? v : w; }
long long bicnd___slonglong__le_cor(bool c, long long a, long long b, long long v, long long w) { return c || a <= b ? v : w; }
long long bicnd___slonglong__le_lad(long long a, long long b, long long v, long long w) { return a <= b && ga ? v : w; }
long long bicnd___slonglong__le_lor(long long a, long long b, long long v, long long w) { return a <= b || ga ? v : w; }
long long bicnd___slonglong__le_sad(long long a, long long b, long long v, long long w) { return a <= b && gv ? v : w; }
long long bicnd___slonglong__le_sor(long long a, long long b, long long v, long long w) { return a <= b || gv ? v : w; }

long long bicnd___slonglong__ge_cnv(long long a, long long b) { return a >= b; }
long long bicnd___slonglong__ge_cpl(long long a, long long b) { return !(a >= b); }
long long bicnd___slonglong__ge_dir(long long a, long long b) { return a >= b ? 1 : 0; }
long long bicnd___slonglong__ge_inv(long long a, long long b) { return a >= b ? 0 : 1; }
long long bicnd___slonglong__ge_sel(long long a, long long b, long long v, long long w) { return a >= b ? v : w; }
long long bicnd___slonglong__ge_jmp(long long a, long long b, long long v, long long w) { return a >= b chess_keep_if ? v : w; }

long long bicnd___slonglong__ge_cad(bool c, long long a, long long b, long long v, long long w) { return c && a >= b ? v : w; }
long long bicnd___slonglong__ge_cor(bool c, long long a, long long b, long long v, long long w) { return c || a >= b ? v : w; }
long long bicnd___slonglong__ge_lad(long long a, long long b, long long v, long long w) { return a >= b && ga ? v : w; }
long long bicnd___slonglong__ge_lor(long long a, long long b, long long v, long long w) { return a >= b || ga ? v : w; }
long long bicnd___slonglong__ge_sad(long long a, long long b, long long v, long long w) { return a >= b && gv ? v : w; }
long long bicnd___slonglong__ge_sor(long long a, long long b, long long v, long long w) { return a >= b || gv ? v : w; }

long long bicnd___slonglong__eq_cnv(long long a, long long b) { return a == b; }
long long bicnd___slonglong__eq_cpl(long long a, long long b) { return !(a == b); }
long long bicnd___slonglong__eq_dir(long long a, long long b) { return a == b ? 1 : 0; }
long long bicnd___slonglong__eq_inv(long long a, long long b) { return a == b ? 0 : 1; }
long long bicnd___slonglong__eq_sel(long long a, long long b, long long v, long long w) { return a == b ? v : w; }
long long bicnd___slonglong__eq_jmp(long long a, long long b, long long v, long long w) { return a == b chess_keep_if ? v : w; }

long long bicnd___slonglong__eq_cad(bool c, long long a, long long b, long long v, long long w) { return c && a == b ? v : w; }
long long bicnd___slonglong__eq_cor(bool c, long long a, long long b, long long v, long long w) { return c || a == b ? v : w; }
long long bicnd___slonglong__eq_lad(long long a, long long b, long long v, long long w) { return a == b && ga ? v : w; }
long long bicnd___slonglong__eq_lor(long long a, long long b, long long v, long long w) { return a == b || ga ? v : w; }
long long bicnd___slonglong__eq_sad(long long a, long long b, long long v, long long w) { return a == b && gv ? v : w; }
long long bicnd___slonglong__eq_sor(long long a, long long b, long long v, long long w) { return a == b || gv ? v : w; }

long long bicnd___slonglong__ne_cnv(long long a, long long b) { return a != b; }
long long bicnd___slonglong__ne_cpl(long long a, long long b) { return !(a != b); }
long long bicnd___slonglong__ne_dir(long long a, long long b) { return a != b ? 1 : 0; }
long long bicnd___slonglong__ne_inv(long long a, long long b) { return a != b ? 0 : 1; }
long long bicnd___slonglong__ne_sel(long long a, long long b, long long v, long long w) { return a != b ? v : w; }
long long bicnd___slonglong__ne_jmp(long long a, long long b, long long v, long long w) { return a != b chess_keep_if ? v : w; }

long long bicnd___slonglong__ne_cad(bool c, long long a, long long b, long long v, long long w) { return c && a != b ? v : w; }
long long bicnd___slonglong__ne_cor(bool c, long long a, long long b, long long v, long long w) { return c || a != b ? v : w; }
long long bicnd___slonglong__ne_lad(long long a, long long b, long long v, long long w) { return a != b && ga ? v : w; }
long long bicnd___slonglong__ne_lor(long long a, long long b, long long v, long long w) { return a != b || ga ? v : w; }
long long bicnd___slonglong__ne_sad(long long a, long long b, long long v, long long w) { return a != b && gv ? v : w; }
long long bicnd___slonglong__ne_sor(long long a, long long b, long long v, long long w) { return a != b || gv ? v : w; }

//-- unsigned long long

unsigned long long bicnd___ulonglong_barg_cnv(bool b) { return b; }
unsigned long long bicnd___ulonglong_barg_cpl(bool b) { return !b; }
unsigned long long bicnd___ulonglong_barg_dir(bool b) { return b ? 1 : 0; }
unsigned long long bicnd___ulonglong_barg_inv(bool b) { return b ? 0 : 1; }
unsigned long long bicnd___ulonglong_barg_sel(bool b, unsigned long long v, unsigned long long w) { return b ? v : w; }
unsigned long long bicnd___ulonglong_barg_jmp(bool b, unsigned long long v, unsigned long long w) { return b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong_barg_cad(bool c, bool b, unsigned long long v, unsigned long long w) { return c && b ? v : w; }
unsigned long long bicnd___ulonglong_barg_cor(bool c, bool b, unsigned long long v, unsigned long long w) { return c || b ? v : w; }
unsigned long long bicnd___ulonglong_barg_lad(bool b, unsigned long long v, unsigned long long w) { return b && ga ? v : w; }
unsigned long long bicnd___ulonglong_barg_lor(bool b, unsigned long long v, unsigned long long w) { return b || ga ? v : w; }
unsigned long long bicnd___ulonglong_barg_sad(bool b, unsigned long long v, unsigned long long w) { return b && gv ? v : w; }
unsigned long long bicnd___ulonglong_barg_sor(bool b, unsigned long long v, unsigned long long w) { return b || gv ? v : w; }

unsigned long long bicnd___ulonglong__lt_cnv(unsigned long long a, unsigned long long b) { return a < b; }
unsigned long long bicnd___ulonglong__lt_cpl(unsigned long long a, unsigned long long b) { return !(a < b); }
unsigned long long bicnd___ulonglong__lt_dir(unsigned long long a, unsigned long long b) { return a < b ? 1 : 0; }
unsigned long long bicnd___ulonglong__lt_inv(unsigned long long a, unsigned long long b) { return a < b ? 0 : 1; }
unsigned long long bicnd___ulonglong__lt_sel(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a < b ? v : w; }
unsigned long long bicnd___ulonglong__lt_jmp(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a < b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong__lt_cad(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c && a < b ? v : w; }
unsigned long long bicnd___ulonglong__lt_cor(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c || a < b ? v : w; }
unsigned long long bicnd___ulonglong__lt_lad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a < b && ga ? v : w; }
unsigned long long bicnd___ulonglong__lt_lor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a < b || ga ? v : w; }
unsigned long long bicnd___ulonglong__lt_sad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a < b && gv ? v : w; }
unsigned long long bicnd___ulonglong__lt_sor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a < b || gv ? v : w; }

unsigned long long bicnd___ulonglong__gt_cnv(unsigned long long a, unsigned long long b) { return a > b; }
unsigned long long bicnd___ulonglong__gt_cpl(unsigned long long a, unsigned long long b) { return !(a > b); }
unsigned long long bicnd___ulonglong__gt_dir(unsigned long long a, unsigned long long b) { return a > b ? 1 : 0; }
unsigned long long bicnd___ulonglong__gt_inv(unsigned long long a, unsigned long long b) { return a > b ? 0 : 1; }
unsigned long long bicnd___ulonglong__gt_sel(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a > b ? v : w; }
unsigned long long bicnd___ulonglong__gt_jmp(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a > b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong__gt_cad(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c && a > b ? v : w; }
unsigned long long bicnd___ulonglong__gt_cor(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c || a > b ? v : w; }
unsigned long long bicnd___ulonglong__gt_lad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a > b && ga ? v : w; }
unsigned long long bicnd___ulonglong__gt_lor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a > b || ga ? v : w; }
unsigned long long bicnd___ulonglong__gt_sad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a > b && gv ? v : w; }
unsigned long long bicnd___ulonglong__gt_sor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a > b || gv ? v : w; }

unsigned long long bicnd___ulonglong__le_cnv(unsigned long long a, unsigned long long b) { return a <= b; }
unsigned long long bicnd___ulonglong__le_cpl(unsigned long long a, unsigned long long b) { return !(a <= b); }
unsigned long long bicnd___ulonglong__le_dir(unsigned long long a, unsigned long long b) { return a <= b ? 1 : 0; }
unsigned long long bicnd___ulonglong__le_inv(unsigned long long a, unsigned long long b) { return a <= b ? 0 : 1; }
unsigned long long bicnd___ulonglong__le_sel(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a <= b ? v : w; }
unsigned long long bicnd___ulonglong__le_jmp(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a <= b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong__le_cad(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c && a <= b ? v : w; }
unsigned long long bicnd___ulonglong__le_cor(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c || a <= b ? v : w; }
unsigned long long bicnd___ulonglong__le_lad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a <= b && ga ? v : w; }
unsigned long long bicnd___ulonglong__le_lor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a <= b || ga ? v : w; }
unsigned long long bicnd___ulonglong__le_sad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a <= b && gv ? v : w; }
unsigned long long bicnd___ulonglong__le_sor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a <= b || gv ? v : w; }

unsigned long long bicnd___ulonglong__ge_cnv(unsigned long long a, unsigned long long b) { return a >= b; }
unsigned long long bicnd___ulonglong__ge_cpl(unsigned long long a, unsigned long long b) { return !(a >= b); }
unsigned long long bicnd___ulonglong__ge_dir(unsigned long long a, unsigned long long b) { return a >= b ? 1 : 0; }
unsigned long long bicnd___ulonglong__ge_inv(unsigned long long a, unsigned long long b) { return a >= b ? 0 : 1; }
unsigned long long bicnd___ulonglong__ge_sel(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a >= b ? v : w; }
unsigned long long bicnd___ulonglong__ge_jmp(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a >= b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong__ge_cad(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c && a >= b ? v : w; }
unsigned long long bicnd___ulonglong__ge_cor(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c || a >= b ? v : w; }
unsigned long long bicnd___ulonglong__ge_lad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a >= b && ga ? v : w; }
unsigned long long bicnd___ulonglong__ge_lor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a >= b || ga ? v : w; }
unsigned long long bicnd___ulonglong__ge_sad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a >= b && gv ? v : w; }
unsigned long long bicnd___ulonglong__ge_sor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a >= b || gv ? v : w; }

unsigned long long bicnd___ulonglong__eq_cnv(unsigned long long a, unsigned long long b) { return a == b; }
unsigned long long bicnd___ulonglong__eq_cpl(unsigned long long a, unsigned long long b) { return !(a == b); }
unsigned long long bicnd___ulonglong__eq_dir(unsigned long long a, unsigned long long b) { return a == b ? 1 : 0; }
unsigned long long bicnd___ulonglong__eq_inv(unsigned long long a, unsigned long long b) { return a == b ? 0 : 1; }
unsigned long long bicnd___ulonglong__eq_sel(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a == b ? v : w; }
unsigned long long bicnd___ulonglong__eq_jmp(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a == b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong__eq_cad(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c && a == b ? v : w; }
unsigned long long bicnd___ulonglong__eq_cor(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c || a == b ? v : w; }
unsigned long long bicnd___ulonglong__eq_lad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a == b && ga ? v : w; }
unsigned long long bicnd___ulonglong__eq_lor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a == b || ga ? v : w; }
unsigned long long bicnd___ulonglong__eq_sad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a == b && gv ? v : w; }
unsigned long long bicnd___ulonglong__eq_sor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a == b || gv ? v : w; }

unsigned long long bicnd___ulonglong__ne_cnv(unsigned long long a, unsigned long long b) { return a != b; }
unsigned long long bicnd___ulonglong__ne_cpl(unsigned long long a, unsigned long long b) { return !(a != b); }
unsigned long long bicnd___ulonglong__ne_dir(unsigned long long a, unsigned long long b) { return a != b ? 1 : 0; }
unsigned long long bicnd___ulonglong__ne_inv(unsigned long long a, unsigned long long b) { return a != b ? 0 : 1; }
unsigned long long bicnd___ulonglong__ne_sel(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a != b ? v : w; }
unsigned long long bicnd___ulonglong__ne_jmp(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a != b chess_keep_if ? v : w; }

unsigned long long bicnd___ulonglong__ne_cad(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c && a != b ? v : w; }
unsigned long long bicnd___ulonglong__ne_cor(bool c, unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return c || a != b ? v : w; }
unsigned long long bicnd___ulonglong__ne_lad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a != b && ga ? v : w; }
unsigned long long bicnd___ulonglong__ne_lor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a != b || ga ? v : w; }
unsigned long long bicnd___ulonglong__ne_sad(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a != b && gv ? v : w; }
unsigned long long bicnd___ulonglong__ne_sor(unsigned long long a, unsigned long long b, unsigned long long v, unsigned long long w) { return a != b || gv ? v : w; }

//-- float

float bicnd___ffloat_barg_cnv(bool b) { return b; }
float bicnd___ffloat_barg_cpl(bool b) { return !b; }
float bicnd___ffloat_barg_dir(bool b) { return b ? 1 : 0; }
float bicnd___ffloat_barg_inv(bool b) { return b ? 0 : 1; }
float bicnd___ffloat_barg_sel(bool b, float v, float w) { return b ? v : w; }
float bicnd___ffloat_barg_jmp(bool b, float v, float w) { return b chess_keep_if ? v : w; }

float bicnd___ffloat_barg_cad(bool c, bool b, float v, float w) { return c && b ? v : w; }
float bicnd___ffloat_barg_cor(bool c, bool b, float v, float w) { return c || b ? v : w; }
float bicnd___ffloat_barg_lad(bool b, float v, float w) { return b && ga ? v : w; }
float bicnd___ffloat_barg_lor(bool b, float v, float w) { return b || ga ? v : w; }
float bicnd___ffloat_barg_sad(bool b, float v, float w) { return b && gv ? v : w; }
float bicnd___ffloat_barg_sor(bool b, float v, float w) { return b || gv ? v : w; }

float bicnd___ffloat__lt_cnv(float a, float b) { return a < b; }
float bicnd___ffloat__lt_cpl(float a, float b) { return !(a < b); }
float bicnd___ffloat__lt_dir(float a, float b) { return a < b ? 1 : 0; }
float bicnd___ffloat__lt_inv(float a, float b) { return a < b ? 0 : 1; }
float bicnd___ffloat__lt_sel(float a, float b, float v, float w) { return a < b ? v : w; }
float bicnd___ffloat__lt_jmp(float a, float b, float v, float w) { return a < b chess_keep_if ? v : w; }

float bicnd___ffloat__lt_cad(bool c, float a, float b, float v, float w) { return c && a < b ? v : w; }
float bicnd___ffloat__lt_cor(bool c, float a, float b, float v, float w) { return c || a < b ? v : w; }
float bicnd___ffloat__lt_lad(float a, float b, float v, float w) { return a < b && ga ? v : w; }
float bicnd___ffloat__lt_lor(float a, float b, float v, float w) { return a < b || ga ? v : w; }
float bicnd___ffloat__lt_sad(float a, float b, float v, float w) { return a < b && gv ? v : w; }
float bicnd___ffloat__lt_sor(float a, float b, float v, float w) { return a < b || gv ? v : w; }

float bicnd___ffloat__gt_cnv(float a, float b) { return a > b; }
float bicnd___ffloat__gt_cpl(float a, float b) { return !(a > b); }
float bicnd___ffloat__gt_dir(float a, float b) { return a > b ? 1 : 0; }
float bicnd___ffloat__gt_inv(float a, float b) { return a > b ? 0 : 1; }
float bicnd___ffloat__gt_sel(float a, float b, float v, float w) { return a > b ? v : w; }
float bicnd___ffloat__gt_jmp(float a, float b, float v, float w) { return a > b chess_keep_if ? v : w; }

float bicnd___ffloat__gt_cad(bool c, float a, float b, float v, float w) { return c && a > b ? v : w; }
float bicnd___ffloat__gt_cor(bool c, float a, float b, float v, float w) { return c || a > b ? v : w; }
float bicnd___ffloat__gt_lad(float a, float b, float v, float w) { return a > b && ga ? v : w; }
float bicnd___ffloat__gt_lor(float a, float b, float v, float w) { return a > b || ga ? v : w; }
float bicnd___ffloat__gt_sad(float a, float b, float v, float w) { return a > b && gv ? v : w; }
float bicnd___ffloat__gt_sor(float a, float b, float v, float w) { return a > b || gv ? v : w; }

float bicnd___ffloat__le_cnv(float a, float b) { return a <= b; }
float bicnd___ffloat__le_cpl(float a, float b) { return !(a <= b); }
float bicnd___ffloat__le_dir(float a, float b) { return a <= b ? 1 : 0; }
float bicnd___ffloat__le_inv(float a, float b) { return a <= b ? 0 : 1; }
float bicnd___ffloat__le_sel(float a, float b, float v, float w) { return a <= b ? v : w; }
float bicnd___ffloat__le_jmp(float a, float b, float v, float w) { return a <= b chess_keep_if ? v : w; }

float bicnd___ffloat__le_cad(bool c, float a, float b, float v, float w) { return c && a <= b ? v : w; }
float bicnd___ffloat__le_cor(bool c, float a, float b, float v, float w) { return c || a <= b ? v : w; }
float bicnd___ffloat__le_lad(float a, float b, float v, float w) { return a <= b && ga ? v : w; }
float bicnd___ffloat__le_lor(float a, float b, float v, float w) { return a <= b || ga ? v : w; }
float bicnd___ffloat__le_sad(float a, float b, float v, float w) { return a <= b && gv ? v : w; }
float bicnd___ffloat__le_sor(float a, float b, float v, float w) { return a <= b || gv ? v : w; }

float bicnd___ffloat__ge_cnv(float a, float b) { return a >= b; }
float bicnd___ffloat__ge_cpl(float a, float b) { return !(a >= b); }
float bicnd___ffloat__ge_dir(float a, float b) { return a >= b ? 1 : 0; }
float bicnd___ffloat__ge_inv(float a, float b) { return a >= b ? 0 : 1; }
float bicnd___ffloat__ge_sel(float a, float b, float v, float w) { return a >= b ? v : w; }
float bicnd___ffloat__ge_jmp(float a, float b, float v, float w) { return a >= b chess_keep_if ? v : w; }

float bicnd___ffloat__ge_cad(bool c, float a, float b, float v, float w) { return c && a >= b ? v : w; }
float bicnd___ffloat__ge_cor(bool c, float a, float b, float v, float w) { return c || a >= b ? v : w; }
float bicnd___ffloat__ge_lad(float a, float b, float v, float w) { return a >= b && ga ? v : w; }
float bicnd___ffloat__ge_lor(float a, float b, float v, float w) { return a >= b || ga ? v : w; }
float bicnd___ffloat__ge_sad(float a, float b, float v, float w) { return a >= b && gv ? v : w; }
float bicnd___ffloat__ge_sor(float a, float b, float v, float w) { return a >= b || gv ? v : w; }

float bicnd___ffloat__eq_cnv(float a, float b) { return a == b; }
float bicnd___ffloat__eq_cpl(float a, float b) { return !(a == b); }
float bicnd___ffloat__eq_dir(float a, float b) { return a == b ? 1 : 0; }
float bicnd___ffloat__eq_inv(float a, float b) { return a == b ? 0 : 1; }
float bicnd___ffloat__eq_sel(float a, float b, float v, float w) { return a == b ? v : w; }
float bicnd___ffloat__eq_jmp(float a, float b, float v, float w) { return a == b chess_keep_if ? v : w; }

float bicnd___ffloat__eq_cad(bool c, float a, float b, float v, float w) { return c && a == b ? v : w; }
float bicnd___ffloat__eq_cor(bool c, float a, float b, float v, float w) { return c || a == b ? v : w; }
float bicnd___ffloat__eq_lad(float a, float b, float v, float w) { return a == b && ga ? v : w; }
float bicnd___ffloat__eq_lor(float a, float b, float v, float w) { return a == b || ga ? v : w; }
float bicnd___ffloat__eq_sad(float a, float b, float v, float w) { return a == b && gv ? v : w; }
float bicnd___ffloat__eq_sor(float a, float b, float v, float w) { return a == b || gv ? v : w; }

float bicnd___ffloat__ne_cnv(float a, float b) { return a != b; }
float bicnd___ffloat__ne_cpl(float a, float b) { return !(a != b); }
float bicnd___ffloat__ne_dir(float a, float b) { return a != b ? 1 : 0; }
float bicnd___ffloat__ne_inv(float a, float b) { return a != b ? 0 : 1; }
float bicnd___ffloat__ne_sel(float a, float b, float v, float w) { return a != b ? v : w; }
float bicnd___ffloat__ne_jmp(float a, float b, float v, float w) { return a != b chess_keep_if ? v : w; }

float bicnd___ffloat__ne_cad(bool c, float a, float b, float v, float w) { return c && a != b ? v : w; }
float bicnd___ffloat__ne_cor(bool c, float a, float b, float v, float w) { return c || a != b ? v : w; }
float bicnd___ffloat__ne_lad(float a, float b, float v, float w) { return a != b && ga ? v : w; }
float bicnd___ffloat__ne_lor(float a, float b, float v, float w) { return a != b || ga ? v : w; }
float bicnd___ffloat__ne_sad(float a, float b, float v, float w) { return a != b && gv ? v : w; }
float bicnd___ffloat__ne_sor(float a, float b, float v, float w) { return a != b || gv ? v : w; }

//-- double

double bicnd___fdouble_barg_cnv(bool b) { return b; }
double bicnd___fdouble_barg_cpl(bool b) { return !b; }
double bicnd___fdouble_barg_dir(bool b) { return b ? 1 : 0; }
double bicnd___fdouble_barg_inv(bool b) { return b ? 0 : 1; }
double bicnd___fdouble_barg_sel(bool b, double v, double w) { return b ? v : w; }
double bicnd___fdouble_barg_jmp(bool b, double v, double w) { return b chess_keep_if ? v : w; }

double bicnd___fdouble_barg_cad(bool c, bool b, double v, double w) { return c && b ? v : w; }
double bicnd___fdouble_barg_cor(bool c, bool b, double v, double w) { return c || b ? v : w; }
double bicnd___fdouble_barg_lad(bool b, double v, double w) { return b && ga ? v : w; }
double bicnd___fdouble_barg_lor(bool b, double v, double w) { return b || ga ? v : w; }
double bicnd___fdouble_barg_sad(bool b, double v, double w) { return b && gv ? v : w; }
double bicnd___fdouble_barg_sor(bool b, double v, double w) { return b || gv ? v : w; }

double bicnd___fdouble__lt_cnv(double a, double b) { return a < b; }
double bicnd___fdouble__lt_cpl(double a, double b) { return !(a < b); }
double bicnd___fdouble__lt_dir(double a, double b) { return a < b ? 1 : 0; }
double bicnd___fdouble__lt_inv(double a, double b) { return a < b ? 0 : 1; }
double bicnd___fdouble__lt_sel(double a, double b, double v, double w) { return a < b ? v : w; }
double bicnd___fdouble__lt_jmp(double a, double b, double v, double w) { return a < b chess_keep_if ? v : w; }

double bicnd___fdouble__lt_cad(bool c, double a, double b, double v, double w) { return c && a < b ? v : w; }
double bicnd___fdouble__lt_cor(bool c, double a, double b, double v, double w) { return c || a < b ? v : w; }
double bicnd___fdouble__lt_lad(double a, double b, double v, double w) { return a < b && ga ? v : w; }
double bicnd___fdouble__lt_lor(double a, double b, double v, double w) { return a < b || ga ? v : w; }
double bicnd___fdouble__lt_sad(double a, double b, double v, double w) { return a < b && gv ? v : w; }
double bicnd___fdouble__lt_sor(double a, double b, double v, double w) { return a < b || gv ? v : w; }

double bicnd___fdouble__gt_cnv(double a, double b) { return a > b; }
double bicnd___fdouble__gt_cpl(double a, double b) { return !(a > b); }
double bicnd___fdouble__gt_dir(double a, double b) { return a > b ? 1 : 0; }
double bicnd___fdouble__gt_inv(double a, double b) { return a > b ? 0 : 1; }
double bicnd___fdouble__gt_sel(double a, double b, double v, double w) { return a > b ? v : w; }
double bicnd___fdouble__gt_jmp(double a, double b, double v, double w) { return a > b chess_keep_if ? v : w; }

double bicnd___fdouble__gt_cad(bool c, double a, double b, double v, double w) { return c && a > b ? v : w; }
double bicnd___fdouble__gt_cor(bool c, double a, double b, double v, double w) { return c || a > b ? v : w; }
double bicnd___fdouble__gt_lad(double a, double b, double v, double w) { return a > b && ga ? v : w; }
double bicnd___fdouble__gt_lor(double a, double b, double v, double w) { return a > b || ga ? v : w; }
double bicnd___fdouble__gt_sad(double a, double b, double v, double w) { return a > b && gv ? v : w; }
double bicnd___fdouble__gt_sor(double a, double b, double v, double w) { return a > b || gv ? v : w; }

double bicnd___fdouble__le_cnv(double a, double b) { return a <= b; }
double bicnd___fdouble__le_cpl(double a, double b) { return !(a <= b); }
double bicnd___fdouble__le_dir(double a, double b) { return a <= b ? 1 : 0; }
double bicnd___fdouble__le_inv(double a, double b) { return a <= b ? 0 : 1; }
double bicnd___fdouble__le_sel(double a, double b, double v, double w) { return a <= b ? v : w; }
double bicnd___fdouble__le_jmp(double a, double b, double v, double w) { return a <= b chess_keep_if ? v : w; }

double bicnd___fdouble__le_cad(bool c, double a, double b, double v, double w) { return c && a <= b ? v : w; }
double bicnd___fdouble__le_cor(bool c, double a, double b, double v, double w) { return c || a <= b ? v : w; }
double bicnd___fdouble__le_lad(double a, double b, double v, double w) { return a <= b && ga ? v : w; }
double bicnd___fdouble__le_lor(double a, double b, double v, double w) { return a <= b || ga ? v : w; }
double bicnd___fdouble__le_sad(double a, double b, double v, double w) { return a <= b && gv ? v : w; }
double bicnd___fdouble__le_sor(double a, double b, double v, double w) { return a <= b || gv ? v : w; }

double bicnd___fdouble__ge_cnv(double a, double b) { return a >= b; }
double bicnd___fdouble__ge_cpl(double a, double b) { return !(a >= b); }
double bicnd___fdouble__ge_dir(double a, double b) { return a >= b ? 1 : 0; }
double bicnd___fdouble__ge_inv(double a, double b) { return a >= b ? 0 : 1; }
double bicnd___fdouble__ge_sel(double a, double b, double v, double w) { return a >= b ? v : w; }
double bicnd___fdouble__ge_jmp(double a, double b, double v, double w) { return a >= b chess_keep_if ? v : w; }

double bicnd___fdouble__ge_cad(bool c, double a, double b, double v, double w) { return c && a >= b ? v : w; }
double bicnd___fdouble__ge_cor(bool c, double a, double b, double v, double w) { return c || a >= b ? v : w; }
double bicnd___fdouble__ge_lad(double a, double b, double v, double w) { return a >= b && ga ? v : w; }
double bicnd___fdouble__ge_lor(double a, double b, double v, double w) { return a >= b || ga ? v : w; }
double bicnd___fdouble__ge_sad(double a, double b, double v, double w) { return a >= b && gv ? v : w; }
double bicnd___fdouble__ge_sor(double a, double b, double v, double w) { return a >= b || gv ? v : w; }

double bicnd___fdouble__eq_cnv(double a, double b) { return a == b; }
double bicnd___fdouble__eq_cpl(double a, double b) { return !(a == b); }
double bicnd___fdouble__eq_dir(double a, double b) { return a == b ? 1 : 0; }
double bicnd___fdouble__eq_inv(double a, double b) { return a == b ? 0 : 1; }
double bicnd___fdouble__eq_sel(double a, double b, double v, double w) { return a == b ? v : w; }
double bicnd___fdouble__eq_jmp(double a, double b, double v, double w) { return a == b chess_keep_if ? v : w; }

double bicnd___fdouble__eq_cad(bool c, double a, double b, double v, double w) { return c && a == b ? v : w; }
double bicnd___fdouble__eq_cor(bool c, double a, double b, double v, double w) { return c || a == b ? v : w; }
double bicnd___fdouble__eq_lad(double a, double b, double v, double w) { return a == b && ga ? v : w; }
double bicnd___fdouble__eq_lor(double a, double b, double v, double w) { return a == b || ga ? v : w; }
double bicnd___fdouble__eq_sad(double a, double b, double v, double w) { return a == b && gv ? v : w; }
double bicnd___fdouble__eq_sor(double a, double b, double v, double w) { return a == b || gv ? v : w; }

double bicnd___fdouble__ne_cnv(double a, double b) { return a != b; }
double bicnd___fdouble__ne_cpl(double a, double b) { return !(a != b); }
double bicnd___fdouble__ne_dir(double a, double b) { return a != b ? 1 : 0; }
double bicnd___fdouble__ne_inv(double a, double b) { return a != b ? 0 : 1; }
double bicnd___fdouble__ne_sel(double a, double b, double v, double w) { return a != b ? v : w; }
double bicnd___fdouble__ne_jmp(double a, double b, double v, double w) { return a != b chess_keep_if ? v : w; }

double bicnd___fdouble__ne_cad(bool c, double a, double b, double v, double w) { return c && a != b ? v : w; }
double bicnd___fdouble__ne_cor(bool c, double a, double b, double v, double w) { return c || a != b ? v : w; }
double bicnd___fdouble__ne_lad(double a, double b, double v, double w) { return a != b && ga ? v : w; }
double bicnd___fdouble__ne_lor(double a, double b, double v, double w) { return a != b || ga ? v : w; }
double bicnd___fdouble__ne_sad(double a, double b, double v, double w) { return a != b && gv ? v : w; }
double bicnd___fdouble__ne_sor(double a, double b, double v, double w) { return a != b || gv ? v : w; }


} //extern "C"  (552 functions)
