
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: full_context_switch.c
// Test full context switch  (requires spilling)
// (Unlike other tests, these functions may generate quite a lot of code.
//  More specific tests can be found in file  register_spilling.c .
//  In particular, check for relevant registers reported to be not spillable.)

extern "C" {

void foo() property(loop_free);


void test_save_restore_all_clobbered_registers() clobbers()
{
    // must save all caller-saved registers
    foo();
    // must restore all caller-saved registers
}


} //extern "C"  (1 functions)
