
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: memory_DMb.c
// Test memory DMb pointer arithmetic stand-alone and with load/store

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {

//-- signed char                // size=1 alignment=1

void pointer_p1___schar_DMb(signed char chess_storage(DMb)*& p) { ++p; }
void pointer_m1___schar_DMb(signed char chess_storage(DMb)*& p) { --p; }
void pointer_pN___schar_DMb(signed char chess_storage(DMb)*& p) { p += N; }
void pointer_mN___schar_DMb(signed char chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___schar_DMb(signed char chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___schar_DMb(signed char chess_storage(DMb)*& p, int i) { p -= i; }

signed char chess_storage(DMb) global___schar_DMb;
signed char chess_storage(DMb) garray___schar_DMb[N+1];

signed char load_global___schar_DMb() { return global___schar_DMb; }
signed char load_garray_pN___schar_DMb() { return garray___schar_DMb[N]; }
signed char load_garray_pI___schar_DMb(int i) { return garray___schar_DMb[i]; }

void store_global___schar_DMb(signed char a) { global___schar_DMb = a; }
void store_garray_pN___schar_DMb(signed char a) { garray___schar_DMb[N] = a; }
void store_garray_pI___schar_DMb(signed char a, int i) { garray___schar_DMb[i] = a; }

signed char chess_storage(DMb_stat) global___schar_DMb_stat;
signed char chess_storage(DMb_stat) garray___schar_DMb_stat[N+1];

signed char load_global___schar_DMb_stat() { return global___schar_DMb_stat; }
signed char load_garray_pN___schar_DMb_stat() { return garray___schar_DMb_stat[N]; }
signed char load_garray_pI___schar_DMb_stat(int i) { return garray___schar_DMb_stat[i]; }

void store_global___schar_DMb_stat(signed char a) { global___schar_DMb_stat = a; }
void store_garray_pN___schar_DMb_stat(signed char a) { garray___schar_DMb_stat[N] = a; }
void store_garray_pI___schar_DMb_stat(signed char a, int i) { garray___schar_DMb_stat[i] = a; }


signed char load_indirect0___schar_DMb(signed char chess_storage(DMb)* p) { return *p; }
signed char load_indexedp1___schar_DMb(signed char chess_storage(DMb)* p) { return p[ 1]; }
signed char load_indexedm1___schar_DMb(signed char chess_storage(DMb)* p) { return p[-1]; }
signed char load_indexedpN___schar_DMb(signed char chess_storage(DMb)* p) { return p[ N]; }
signed char load_indexedmN___schar_DMb(signed char chess_storage(DMb)* p) { return p[-N]; }
signed char load_indexedpI___schar_DMb(signed char chess_storage(DMb)* p, int i) { return p[ i]; }
signed char load_indexedmI___schar_DMb(signed char chess_storage(DMb)* p, int i) { return p[-i]; }

signed char load_postmodp1___schar_DMb(signed char chess_storage(DMb)*& p) { return *p++; }
signed char load_postmodm1___schar_DMb(signed char chess_storage(DMb)*& p) { return *p--; }
signed char load_postmodpN___schar_DMb(signed char chess_storage(DMb)*& p) { signed char t = *p; p += N; return t; }
signed char load_postmodmN___schar_DMb(signed char chess_storage(DMb)*& p) { signed char t = *p; p -= N; return t; }
signed char load_postmodpI___schar_DMb(signed char chess_storage(DMb)*& p, int i) { signed char t = *p; p += i; return t; }
signed char load_postmodmI___schar_DMb(signed char chess_storage(DMb)*& p, int i) { signed char t = *p; p -= i; return t; }

signed char load_premod_p1___schar_DMb(signed char chess_storage(DMb)*& p) { return *++p; }
signed char load_premod_m1___schar_DMb(signed char chess_storage(DMb)*& p) { return *--p; }
signed char load_premod_pN___schar_DMb(signed char chess_storage(DMb)*& p) { p += N; return *p; }
signed char load_premod_mN___schar_DMb(signed char chess_storage(DMb)*& p) { p -= N; return *p; }
signed char load_premod_pI___schar_DMb(signed char chess_storage(DMb)*& p, int i) { p += i; return *p; }
signed char load_premod_mI___schar_DMb(signed char chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___schar_DMb(signed char a, signed char chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___schar_DMb(signed char a, signed char chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___schar_DMb(signed char a, signed char chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___schar_DMb(signed char a, signed char chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___schar_DMb(signed char a, signed char chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___schar_DMb(signed char a, signed char chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___schar_DMb(signed char a, signed char chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___schar_DMb(signed char a, signed char chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___schar_DMb(signed char a, signed char chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___schar_DMb(signed char a, signed char chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___schar_DMb(signed char a, signed char chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___schar_DMb(signed char a, signed char chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- unsigned char              // size=1 alignment=1

void pointer_p1___uchar_DMb(unsigned char chess_storage(DMb)*& p) { ++p; }
void pointer_m1___uchar_DMb(unsigned char chess_storage(DMb)*& p) { --p; }
void pointer_pN___uchar_DMb(unsigned char chess_storage(DMb)*& p) { p += N; }
void pointer_mN___uchar_DMb(unsigned char chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___uchar_DMb(unsigned char chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___uchar_DMb(unsigned char chess_storage(DMb)*& p, int i) { p -= i; }

unsigned char chess_storage(DMb) global___uchar_DMb;
unsigned char chess_storage(DMb) garray___uchar_DMb[N+1];

unsigned char load_global___uchar_DMb() { return global___uchar_DMb; }
unsigned char load_garray_pN___uchar_DMb() { return garray___uchar_DMb[N]; }
unsigned char load_garray_pI___uchar_DMb(int i) { return garray___uchar_DMb[i]; }

void store_global___uchar_DMb(unsigned char a) { global___uchar_DMb = a; }
void store_garray_pN___uchar_DMb(unsigned char a) { garray___uchar_DMb[N] = a; }
void store_garray_pI___uchar_DMb(unsigned char a, int i) { garray___uchar_DMb[i] = a; }

unsigned char chess_storage(DMb_stat) global___uchar_DMb_stat;
unsigned char chess_storage(DMb_stat) garray___uchar_DMb_stat[N+1];

unsigned char load_global___uchar_DMb_stat() { return global___uchar_DMb_stat; }
unsigned char load_garray_pN___uchar_DMb_stat() { return garray___uchar_DMb_stat[N]; }
unsigned char load_garray_pI___uchar_DMb_stat(int i) { return garray___uchar_DMb_stat[i]; }

void store_global___uchar_DMb_stat(unsigned char a) { global___uchar_DMb_stat = a; }
void store_garray_pN___uchar_DMb_stat(unsigned char a) { garray___uchar_DMb_stat[N] = a; }
void store_garray_pI___uchar_DMb_stat(unsigned char a, int i) { garray___uchar_DMb_stat[i] = a; }


unsigned char load_indirect0___uchar_DMb(unsigned char chess_storage(DMb)* p) { return *p; }
unsigned char load_indexedp1___uchar_DMb(unsigned char chess_storage(DMb)* p) { return p[ 1]; }
unsigned char load_indexedm1___uchar_DMb(unsigned char chess_storage(DMb)* p) { return p[-1]; }
unsigned char load_indexedpN___uchar_DMb(unsigned char chess_storage(DMb)* p) { return p[ N]; }
unsigned char load_indexedmN___uchar_DMb(unsigned char chess_storage(DMb)* p) { return p[-N]; }
unsigned char load_indexedpI___uchar_DMb(unsigned char chess_storage(DMb)* p, int i) { return p[ i]; }
unsigned char load_indexedmI___uchar_DMb(unsigned char chess_storage(DMb)* p, int i) { return p[-i]; }

unsigned char load_postmodp1___uchar_DMb(unsigned char chess_storage(DMb)*& p) { return *p++; }
unsigned char load_postmodm1___uchar_DMb(unsigned char chess_storage(DMb)*& p) { return *p--; }
unsigned char load_postmodpN___uchar_DMb(unsigned char chess_storage(DMb)*& p) { unsigned char t = *p; p += N; return t; }
unsigned char load_postmodmN___uchar_DMb(unsigned char chess_storage(DMb)*& p) { unsigned char t = *p; p -= N; return t; }
unsigned char load_postmodpI___uchar_DMb(unsigned char chess_storage(DMb)*& p, int i) { unsigned char t = *p; p += i; return t; }
unsigned char load_postmodmI___uchar_DMb(unsigned char chess_storage(DMb)*& p, int i) { unsigned char t = *p; p -= i; return t; }

unsigned char load_premod_p1___uchar_DMb(unsigned char chess_storage(DMb)*& p) { return *++p; }
unsigned char load_premod_m1___uchar_DMb(unsigned char chess_storage(DMb)*& p) { return *--p; }
unsigned char load_premod_pN___uchar_DMb(unsigned char chess_storage(DMb)*& p) { p += N; return *p; }
unsigned char load_premod_mN___uchar_DMb(unsigned char chess_storage(DMb)*& p) { p -= N; return *p; }
unsigned char load_premod_pI___uchar_DMb(unsigned char chess_storage(DMb)*& p, int i) { p += i; return *p; }
unsigned char load_premod_mI___uchar_DMb(unsigned char chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___uchar_DMb(unsigned char a, unsigned char chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- short                      // size=2 alignment=2

void pointer_p1___sshort_DMb(short chess_storage(DMb)*& p) { ++p; }
void pointer_m1___sshort_DMb(short chess_storage(DMb)*& p) { --p; }
void pointer_pN___sshort_DMb(short chess_storage(DMb)*& p) { p += N; }
void pointer_mN___sshort_DMb(short chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___sshort_DMb(short chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___sshort_DMb(short chess_storage(DMb)*& p, int i) { p -= i; }

short chess_storage(DMb) global___sshort_DMb;
short chess_storage(DMb) garray___sshort_DMb[N+1];

short load_global___sshort_DMb() { return global___sshort_DMb; }
short load_garray_pN___sshort_DMb() { return garray___sshort_DMb[N]; }
short load_garray_pI___sshort_DMb(int i) { return garray___sshort_DMb[i]; }

void store_global___sshort_DMb(short a) { global___sshort_DMb = a; }
void store_garray_pN___sshort_DMb(short a) { garray___sshort_DMb[N] = a; }
void store_garray_pI___sshort_DMb(short a, int i) { garray___sshort_DMb[i] = a; }

short chess_storage(DMb_stat) global___sshort_DMb_stat;
short chess_storage(DMb_stat) garray___sshort_DMb_stat[N+1];

short load_global___sshort_DMb_stat() { return global___sshort_DMb_stat; }
short load_garray_pN___sshort_DMb_stat() { return garray___sshort_DMb_stat[N]; }
short load_garray_pI___sshort_DMb_stat(int i) { return garray___sshort_DMb_stat[i]; }

void store_global___sshort_DMb_stat(short a) { global___sshort_DMb_stat = a; }
void store_garray_pN___sshort_DMb_stat(short a) { garray___sshort_DMb_stat[N] = a; }
void store_garray_pI___sshort_DMb_stat(short a, int i) { garray___sshort_DMb_stat[i] = a; }


short load_indirect0___sshort_DMb(short chess_storage(DMb)* p) { return *p; }
short load_indexedp1___sshort_DMb(short chess_storage(DMb)* p) { return p[ 1]; }
short load_indexedm1___sshort_DMb(short chess_storage(DMb)* p) { return p[-1]; }
short load_indexedpN___sshort_DMb(short chess_storage(DMb)* p) { return p[ N]; }
short load_indexedmN___sshort_DMb(short chess_storage(DMb)* p) { return p[-N]; }
short load_indexedpI___sshort_DMb(short chess_storage(DMb)* p, int i) { return p[ i]; }
short load_indexedmI___sshort_DMb(short chess_storage(DMb)* p, int i) { return p[-i]; }

short load_postmodp1___sshort_DMb(short chess_storage(DMb)*& p) { return *p++; }
short load_postmodm1___sshort_DMb(short chess_storage(DMb)*& p) { return *p--; }
short load_postmodpN___sshort_DMb(short chess_storage(DMb)*& p) { short t = *p; p += N; return t; }
short load_postmodmN___sshort_DMb(short chess_storage(DMb)*& p) { short t = *p; p -= N; return t; }
short load_postmodpI___sshort_DMb(short chess_storage(DMb)*& p, int i) { short t = *p; p += i; return t; }
short load_postmodmI___sshort_DMb(short chess_storage(DMb)*& p, int i) { short t = *p; p -= i; return t; }

short load_premod_p1___sshort_DMb(short chess_storage(DMb)*& p) { return *++p; }
short load_premod_m1___sshort_DMb(short chess_storage(DMb)*& p) { return *--p; }
short load_premod_pN___sshort_DMb(short chess_storage(DMb)*& p) { p += N; return *p; }
short load_premod_mN___sshort_DMb(short chess_storage(DMb)*& p) { p -= N; return *p; }
short load_premod_pI___sshort_DMb(short chess_storage(DMb)*& p, int i) { p += i; return *p; }
short load_premod_mI___sshort_DMb(short chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___sshort_DMb(short a, short chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___sshort_DMb(short a, short chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___sshort_DMb(short a, short chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___sshort_DMb(short a, short chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___sshort_DMb(short a, short chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___sshort_DMb(short a, short chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___sshort_DMb(short a, short chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___sshort_DMb(short a, short chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___sshort_DMb(short a, short chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___sshort_DMb(short a, short chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___sshort_DMb(short a, short chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___sshort_DMb(short a, short chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___sshort_DMb(short a, short chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___sshort_DMb(short a, short chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___sshort_DMb(short a, short chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___sshort_DMb(short a, short chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___sshort_DMb(short a, short chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___sshort_DMb(short a, short chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___sshort_DMb(short a, short chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- unsigned short             // size=2 alignment=2

void pointer_p1___ushort_DMb(unsigned short chess_storage(DMb)*& p) { ++p; }
void pointer_m1___ushort_DMb(unsigned short chess_storage(DMb)*& p) { --p; }
void pointer_pN___ushort_DMb(unsigned short chess_storage(DMb)*& p) { p += N; }
void pointer_mN___ushort_DMb(unsigned short chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___ushort_DMb(unsigned short chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___ushort_DMb(unsigned short chess_storage(DMb)*& p, int i) { p -= i; }

unsigned short chess_storage(DMb) global___ushort_DMb;
unsigned short chess_storage(DMb) garray___ushort_DMb[N+1];

unsigned short load_global___ushort_DMb() { return global___ushort_DMb; }
unsigned short load_garray_pN___ushort_DMb() { return garray___ushort_DMb[N]; }
unsigned short load_garray_pI___ushort_DMb(int i) { return garray___ushort_DMb[i]; }

void store_global___ushort_DMb(unsigned short a) { global___ushort_DMb = a; }
void store_garray_pN___ushort_DMb(unsigned short a) { garray___ushort_DMb[N] = a; }
void store_garray_pI___ushort_DMb(unsigned short a, int i) { garray___ushort_DMb[i] = a; }

unsigned short chess_storage(DMb_stat) global___ushort_DMb_stat;
unsigned short chess_storage(DMb_stat) garray___ushort_DMb_stat[N+1];

unsigned short load_global___ushort_DMb_stat() { return global___ushort_DMb_stat; }
unsigned short load_garray_pN___ushort_DMb_stat() { return garray___ushort_DMb_stat[N]; }
unsigned short load_garray_pI___ushort_DMb_stat(int i) { return garray___ushort_DMb_stat[i]; }

void store_global___ushort_DMb_stat(unsigned short a) { global___ushort_DMb_stat = a; }
void store_garray_pN___ushort_DMb_stat(unsigned short a) { garray___ushort_DMb_stat[N] = a; }
void store_garray_pI___ushort_DMb_stat(unsigned short a, int i) { garray___ushort_DMb_stat[i] = a; }


unsigned short load_indirect0___ushort_DMb(unsigned short chess_storage(DMb)* p) { return *p; }
unsigned short load_indexedp1___ushort_DMb(unsigned short chess_storage(DMb)* p) { return p[ 1]; }
unsigned short load_indexedm1___ushort_DMb(unsigned short chess_storage(DMb)* p) { return p[-1]; }
unsigned short load_indexedpN___ushort_DMb(unsigned short chess_storage(DMb)* p) { return p[ N]; }
unsigned short load_indexedmN___ushort_DMb(unsigned short chess_storage(DMb)* p) { return p[-N]; }
unsigned short load_indexedpI___ushort_DMb(unsigned short chess_storage(DMb)* p, int i) { return p[ i]; }
unsigned short load_indexedmI___ushort_DMb(unsigned short chess_storage(DMb)* p, int i) { return p[-i]; }

unsigned short load_postmodp1___ushort_DMb(unsigned short chess_storage(DMb)*& p) { return *p++; }
unsigned short load_postmodm1___ushort_DMb(unsigned short chess_storage(DMb)*& p) { return *p--; }
unsigned short load_postmodpN___ushort_DMb(unsigned short chess_storage(DMb)*& p) { unsigned short t = *p; p += N; return t; }
unsigned short load_postmodmN___ushort_DMb(unsigned short chess_storage(DMb)*& p) { unsigned short t = *p; p -= N; return t; }
unsigned short load_postmodpI___ushort_DMb(unsigned short chess_storage(DMb)*& p, int i) { unsigned short t = *p; p += i; return t; }
unsigned short load_postmodmI___ushort_DMb(unsigned short chess_storage(DMb)*& p, int i) { unsigned short t = *p; p -= i; return t; }

unsigned short load_premod_p1___ushort_DMb(unsigned short chess_storage(DMb)*& p) { return *++p; }
unsigned short load_premod_m1___ushort_DMb(unsigned short chess_storage(DMb)*& p) { return *--p; }
unsigned short load_premod_pN___ushort_DMb(unsigned short chess_storage(DMb)*& p) { p += N; return *p; }
unsigned short load_premod_mN___ushort_DMb(unsigned short chess_storage(DMb)*& p) { p -= N; return *p; }
unsigned short load_premod_pI___ushort_DMb(unsigned short chess_storage(DMb)*& p, int i) { p += i; return *p; }
unsigned short load_premod_mI___ushort_DMb(unsigned short chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___ushort_DMb(unsigned short a, unsigned short chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- int                        // size=4 alignment=4

void pointer_p1___sint_DMb(int chess_storage(DMb)*& p) { ++p; }
void pointer_m1___sint_DMb(int chess_storage(DMb)*& p) { --p; }
void pointer_pN___sint_DMb(int chess_storage(DMb)*& p) { p += N; }
void pointer_mN___sint_DMb(int chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___sint_DMb(int chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___sint_DMb(int chess_storage(DMb)*& p, int i) { p -= i; }

int chess_storage(DMb) global___sint_DMb;
int chess_storage(DMb) garray___sint_DMb[N+1];

int load_global___sint_DMb() { return global___sint_DMb; }
int load_garray_pN___sint_DMb() { return garray___sint_DMb[N]; }
int load_garray_pI___sint_DMb(int i) { return garray___sint_DMb[i]; }

void store_global___sint_DMb(int a) { global___sint_DMb = a; }
void store_garray_pN___sint_DMb(int a) { garray___sint_DMb[N] = a; }
void store_garray_pI___sint_DMb(int a, int i) { garray___sint_DMb[i] = a; }

int chess_storage(DMb_stat) global___sint_DMb_stat;
int chess_storage(DMb_stat) garray___sint_DMb_stat[N+1];

int load_global___sint_DMb_stat() { return global___sint_DMb_stat; }
int load_garray_pN___sint_DMb_stat() { return garray___sint_DMb_stat[N]; }
int load_garray_pI___sint_DMb_stat(int i) { return garray___sint_DMb_stat[i]; }

void store_global___sint_DMb_stat(int a) { global___sint_DMb_stat = a; }
void store_garray_pN___sint_DMb_stat(int a) { garray___sint_DMb_stat[N] = a; }
void store_garray_pI___sint_DMb_stat(int a, int i) { garray___sint_DMb_stat[i] = a; }


int load_indirect0___sint_DMb(int chess_storage(DMb)* p) { return *p; }
int load_indexedp1___sint_DMb(int chess_storage(DMb)* p) { return p[ 1]; }
int load_indexedm1___sint_DMb(int chess_storage(DMb)* p) { return p[-1]; }
int load_indexedpN___sint_DMb(int chess_storage(DMb)* p) { return p[ N]; }
int load_indexedmN___sint_DMb(int chess_storage(DMb)* p) { return p[-N]; }
int load_indexedpI___sint_DMb(int chess_storage(DMb)* p, int i) { return p[ i]; }
int load_indexedmI___sint_DMb(int chess_storage(DMb)* p, int i) { return p[-i]; }

int load_postmodp1___sint_DMb(int chess_storage(DMb)*& p) { return *p++; }
int load_postmodm1___sint_DMb(int chess_storage(DMb)*& p) { return *p--; }
int load_postmodpN___sint_DMb(int chess_storage(DMb)*& p) { int t = *p; p += N; return t; }
int load_postmodmN___sint_DMb(int chess_storage(DMb)*& p) { int t = *p; p -= N; return t; }
int load_postmodpI___sint_DMb(int chess_storage(DMb)*& p, int i) { int t = *p; p += i; return t; }
int load_postmodmI___sint_DMb(int chess_storage(DMb)*& p, int i) { int t = *p; p -= i; return t; }

int load_premod_p1___sint_DMb(int chess_storage(DMb)*& p) { return *++p; }
int load_premod_m1___sint_DMb(int chess_storage(DMb)*& p) { return *--p; }
int load_premod_pN___sint_DMb(int chess_storage(DMb)*& p) { p += N; return *p; }
int load_premod_mN___sint_DMb(int chess_storage(DMb)*& p) { p -= N; return *p; }
int load_premod_pI___sint_DMb(int chess_storage(DMb)*& p, int i) { p += i; return *p; }
int load_premod_mI___sint_DMb(int chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___sint_DMb(int a, int chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___sint_DMb(int a, int chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___sint_DMb(int a, int chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___sint_DMb(int a, int chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___sint_DMb(int a, int chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___sint_DMb(int a, int chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___sint_DMb(int a, int chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___sint_DMb(int a, int chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___sint_DMb(int a, int chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___sint_DMb(int a, int chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___sint_DMb(int a, int chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___sint_DMb(int a, int chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___sint_DMb(int a, int chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___sint_DMb(int a, int chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___sint_DMb(int a, int chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___sint_DMb(int a, int chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___sint_DMb(int a, int chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___sint_DMb(int a, int chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___sint_DMb(int a, int chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- unsigned                   // size=4 alignment=4

void pointer_p1___uint_DMb(unsigned chess_storage(DMb)*& p) { ++p; }
void pointer_m1___uint_DMb(unsigned chess_storage(DMb)*& p) { --p; }
void pointer_pN___uint_DMb(unsigned chess_storage(DMb)*& p) { p += N; }
void pointer_mN___uint_DMb(unsigned chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___uint_DMb(unsigned chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___uint_DMb(unsigned chess_storage(DMb)*& p, int i) { p -= i; }

unsigned chess_storage(DMb) global___uint_DMb;
unsigned chess_storage(DMb) garray___uint_DMb[N+1];

unsigned load_global___uint_DMb() { return global___uint_DMb; }
unsigned load_garray_pN___uint_DMb() { return garray___uint_DMb[N]; }
unsigned load_garray_pI___uint_DMb(int i) { return garray___uint_DMb[i]; }

void store_global___uint_DMb(unsigned a) { global___uint_DMb = a; }
void store_garray_pN___uint_DMb(unsigned a) { garray___uint_DMb[N] = a; }
void store_garray_pI___uint_DMb(unsigned a, int i) { garray___uint_DMb[i] = a; }

unsigned chess_storage(DMb_stat) global___uint_DMb_stat;
unsigned chess_storage(DMb_stat) garray___uint_DMb_stat[N+1];

unsigned load_global___uint_DMb_stat() { return global___uint_DMb_stat; }
unsigned load_garray_pN___uint_DMb_stat() { return garray___uint_DMb_stat[N]; }
unsigned load_garray_pI___uint_DMb_stat(int i) { return garray___uint_DMb_stat[i]; }

void store_global___uint_DMb_stat(unsigned a) { global___uint_DMb_stat = a; }
void store_garray_pN___uint_DMb_stat(unsigned a) { garray___uint_DMb_stat[N] = a; }
void store_garray_pI___uint_DMb_stat(unsigned a, int i) { garray___uint_DMb_stat[i] = a; }


unsigned load_indirect0___uint_DMb(unsigned chess_storage(DMb)* p) { return *p; }
unsigned load_indexedp1___uint_DMb(unsigned chess_storage(DMb)* p) { return p[ 1]; }
unsigned load_indexedm1___uint_DMb(unsigned chess_storage(DMb)* p) { return p[-1]; }
unsigned load_indexedpN___uint_DMb(unsigned chess_storage(DMb)* p) { return p[ N]; }
unsigned load_indexedmN___uint_DMb(unsigned chess_storage(DMb)* p) { return p[-N]; }
unsigned load_indexedpI___uint_DMb(unsigned chess_storage(DMb)* p, int i) { return p[ i]; }
unsigned load_indexedmI___uint_DMb(unsigned chess_storage(DMb)* p, int i) { return p[-i]; }

unsigned load_postmodp1___uint_DMb(unsigned chess_storage(DMb)*& p) { return *p++; }
unsigned load_postmodm1___uint_DMb(unsigned chess_storage(DMb)*& p) { return *p--; }
unsigned load_postmodpN___uint_DMb(unsigned chess_storage(DMb)*& p) { unsigned t = *p; p += N; return t; }
unsigned load_postmodmN___uint_DMb(unsigned chess_storage(DMb)*& p) { unsigned t = *p; p -= N; return t; }
unsigned load_postmodpI___uint_DMb(unsigned chess_storage(DMb)*& p, int i) { unsigned t = *p; p += i; return t; }
unsigned load_postmodmI___uint_DMb(unsigned chess_storage(DMb)*& p, int i) { unsigned t = *p; p -= i; return t; }

unsigned load_premod_p1___uint_DMb(unsigned chess_storage(DMb)*& p) { return *++p; }
unsigned load_premod_m1___uint_DMb(unsigned chess_storage(DMb)*& p) { return *--p; }
unsigned load_premod_pN___uint_DMb(unsigned chess_storage(DMb)*& p) { p += N; return *p; }
unsigned load_premod_mN___uint_DMb(unsigned chess_storage(DMb)*& p) { p -= N; return *p; }
unsigned load_premod_pI___uint_DMb(unsigned chess_storage(DMb)*& p, int i) { p += i; return *p; }
unsigned load_premod_mI___uint_DMb(unsigned chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___uint_DMb(unsigned a, unsigned chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___uint_DMb(unsigned a, unsigned chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- long long                  // size=8 alignment=4

void pointer_p1___slonglong_DMb(long long chess_storage(DMb)*& p) { ++p; }
void pointer_m1___slonglong_DMb(long long chess_storage(DMb)*& p) { --p; }
void pointer_pN___slonglong_DMb(long long chess_storage(DMb)*& p) { p += N; }
void pointer_mN___slonglong_DMb(long long chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___slonglong_DMb(long long chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___slonglong_DMb(long long chess_storage(DMb)*& p, int i) { p -= i; }

long long chess_storage(DMb) global___slonglong_DMb;
long long chess_storage(DMb) garray___slonglong_DMb[N+1];

long long load_global___slonglong_DMb() { return global___slonglong_DMb; }
long long load_garray_pN___slonglong_DMb() { return garray___slonglong_DMb[N]; }
long long load_garray_pI___slonglong_DMb(int i) { return garray___slonglong_DMb[i]; }

void store_global___slonglong_DMb(long long a) { global___slonglong_DMb = a; }
void store_garray_pN___slonglong_DMb(long long a) { garray___slonglong_DMb[N] = a; }
void store_garray_pI___slonglong_DMb(long long a, int i) { garray___slonglong_DMb[i] = a; }

long long chess_storage(DMb_stat) global___slonglong_DMb_stat;
long long chess_storage(DMb_stat) garray___slonglong_DMb_stat[N+1];

long long load_global___slonglong_DMb_stat() { return global___slonglong_DMb_stat; }
long long load_garray_pN___slonglong_DMb_stat() { return garray___slonglong_DMb_stat[N]; }
long long load_garray_pI___slonglong_DMb_stat(int i) { return garray___slonglong_DMb_stat[i]; }

void store_global___slonglong_DMb_stat(long long a) { global___slonglong_DMb_stat = a; }
void store_garray_pN___slonglong_DMb_stat(long long a) { garray___slonglong_DMb_stat[N] = a; }
void store_garray_pI___slonglong_DMb_stat(long long a, int i) { garray___slonglong_DMb_stat[i] = a; }


long long load_indirect0___slonglong_DMb(long long chess_storage(DMb)* p) { return *p; }
long long load_indexedp1___slonglong_DMb(long long chess_storage(DMb)* p) { return p[ 1]; }
long long load_indexedm1___slonglong_DMb(long long chess_storage(DMb)* p) { return p[-1]; }
long long load_indexedpN___slonglong_DMb(long long chess_storage(DMb)* p) { return p[ N]; }
long long load_indexedmN___slonglong_DMb(long long chess_storage(DMb)* p) { return p[-N]; }
long long load_indexedpI___slonglong_DMb(long long chess_storage(DMb)* p, int i) { return p[ i]; }
long long load_indexedmI___slonglong_DMb(long long chess_storage(DMb)* p, int i) { return p[-i]; }

long long load_postmodp1___slonglong_DMb(long long chess_storage(DMb)*& p) { return *p++; }
long long load_postmodm1___slonglong_DMb(long long chess_storage(DMb)*& p) { return *p--; }
long long load_postmodpN___slonglong_DMb(long long chess_storage(DMb)*& p) { long long t = *p; p += N; return t; }
long long load_postmodmN___slonglong_DMb(long long chess_storage(DMb)*& p) { long long t = *p; p -= N; return t; }
long long load_postmodpI___slonglong_DMb(long long chess_storage(DMb)*& p, int i) { long long t = *p; p += i; return t; }
long long load_postmodmI___slonglong_DMb(long long chess_storage(DMb)*& p, int i) { long long t = *p; p -= i; return t; }

long long load_premod_p1___slonglong_DMb(long long chess_storage(DMb)*& p) { return *++p; }
long long load_premod_m1___slonglong_DMb(long long chess_storage(DMb)*& p) { return *--p; }
long long load_premod_pN___slonglong_DMb(long long chess_storage(DMb)*& p) { p += N; return *p; }
long long load_premod_mN___slonglong_DMb(long long chess_storage(DMb)*& p) { p -= N; return *p; }
long long load_premod_pI___slonglong_DMb(long long chess_storage(DMb)*& p, int i) { p += i; return *p; }
long long load_premod_mI___slonglong_DMb(long long chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___slonglong_DMb(long long a, long long chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___slonglong_DMb(long long a, long long chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___slonglong_DMb(long long a, long long chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___slonglong_DMb(long long a, long long chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___slonglong_DMb(long long a, long long chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___slonglong_DMb(long long a, long long chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___slonglong_DMb(long long a, long long chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___slonglong_DMb(long long a, long long chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___slonglong_DMb(long long a, long long chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___slonglong_DMb(long long a, long long chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___slonglong_DMb(long long a, long long chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___slonglong_DMb(long long a, long long chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- unsigned long long         // size=8 alignment=4

void pointer_p1___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { ++p; }
void pointer_m1___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { --p; }
void pointer_pN___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { p += N; }
void pointer_mN___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p, int i) { p -= i; }

unsigned long long chess_storage(DMb) global___ulonglong_DMb;
unsigned long long chess_storage(DMb) garray___ulonglong_DMb[N+1];

unsigned long long load_global___ulonglong_DMb() { return global___ulonglong_DMb; }
unsigned long long load_garray_pN___ulonglong_DMb() { return garray___ulonglong_DMb[N]; }
unsigned long long load_garray_pI___ulonglong_DMb(int i) { return garray___ulonglong_DMb[i]; }

void store_global___ulonglong_DMb(unsigned long long a) { global___ulonglong_DMb = a; }
void store_garray_pN___ulonglong_DMb(unsigned long long a) { garray___ulonglong_DMb[N] = a; }
void store_garray_pI___ulonglong_DMb(unsigned long long a, int i) { garray___ulonglong_DMb[i] = a; }

unsigned long long chess_storage(DMb_stat) global___ulonglong_DMb_stat;
unsigned long long chess_storage(DMb_stat) garray___ulonglong_DMb_stat[N+1];

unsigned long long load_global___ulonglong_DMb_stat() { return global___ulonglong_DMb_stat; }
unsigned long long load_garray_pN___ulonglong_DMb_stat() { return garray___ulonglong_DMb_stat[N]; }
unsigned long long load_garray_pI___ulonglong_DMb_stat(int i) { return garray___ulonglong_DMb_stat[i]; }

void store_global___ulonglong_DMb_stat(unsigned long long a) { global___ulonglong_DMb_stat = a; }
void store_garray_pN___ulonglong_DMb_stat(unsigned long long a) { garray___ulonglong_DMb_stat[N] = a; }
void store_garray_pI___ulonglong_DMb_stat(unsigned long long a, int i) { garray___ulonglong_DMb_stat[i] = a; }


unsigned long long load_indirect0___ulonglong_DMb(unsigned long long chess_storage(DMb)* p) { return *p; }
unsigned long long load_indexedp1___ulonglong_DMb(unsigned long long chess_storage(DMb)* p) { return p[ 1]; }
unsigned long long load_indexedm1___ulonglong_DMb(unsigned long long chess_storage(DMb)* p) { return p[-1]; }
unsigned long long load_indexedpN___ulonglong_DMb(unsigned long long chess_storage(DMb)* p) { return p[ N]; }
unsigned long long load_indexedmN___ulonglong_DMb(unsigned long long chess_storage(DMb)* p) { return p[-N]; }
unsigned long long load_indexedpI___ulonglong_DMb(unsigned long long chess_storage(DMb)* p, int i) { return p[ i]; }
unsigned long long load_indexedmI___ulonglong_DMb(unsigned long long chess_storage(DMb)* p, int i) { return p[-i]; }

unsigned long long load_postmodp1___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { return *p++; }
unsigned long long load_postmodm1___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { return *p--; }
unsigned long long load_postmodpN___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { unsigned long long t = *p; p += N; return t; }
unsigned long long load_postmodmN___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { unsigned long long t = *p; p -= N; return t; }
unsigned long long load_postmodpI___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p, int i) { unsigned long long t = *p; p += i; return t; }
unsigned long long load_postmodmI___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p, int i) { unsigned long long t = *p; p -= i; return t; }

unsigned long long load_premod_p1___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { return *++p; }
unsigned long long load_premod_m1___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { return *--p; }
unsigned long long load_premod_pN___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { p += N; return *p; }
unsigned long long load_premod_mN___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p) { p -= N; return *p; }
unsigned long long load_premod_pI___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p, int i) { p += i; return *p; }
unsigned long long load_premod_mI___ulonglong_DMb(unsigned long long chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___ulonglong_DMb(unsigned long long a, unsigned long long chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- float                      // size=4 alignment=4

void pointer_p1___ffloat_DMb(float chess_storage(DMb)*& p) { ++p; }
void pointer_m1___ffloat_DMb(float chess_storage(DMb)*& p) { --p; }
void pointer_pN___ffloat_DMb(float chess_storage(DMb)*& p) { p += N; }
void pointer_mN___ffloat_DMb(float chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___ffloat_DMb(float chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___ffloat_DMb(float chess_storage(DMb)*& p, int i) { p -= i; }

float chess_storage(DMb) global___ffloat_DMb;
float chess_storage(DMb) garray___ffloat_DMb[N+1];

float load_global___ffloat_DMb() { return global___ffloat_DMb; }
float load_garray_pN___ffloat_DMb() { return garray___ffloat_DMb[N]; }
float load_garray_pI___ffloat_DMb(int i) { return garray___ffloat_DMb[i]; }

void store_global___ffloat_DMb(float a) { global___ffloat_DMb = a; }
void store_garray_pN___ffloat_DMb(float a) { garray___ffloat_DMb[N] = a; }
void store_garray_pI___ffloat_DMb(float a, int i) { garray___ffloat_DMb[i] = a; }

float chess_storage(DMb_stat) global___ffloat_DMb_stat;
float chess_storage(DMb_stat) garray___ffloat_DMb_stat[N+1];

float load_global___ffloat_DMb_stat() { return global___ffloat_DMb_stat; }
float load_garray_pN___ffloat_DMb_stat() { return garray___ffloat_DMb_stat[N]; }
float load_garray_pI___ffloat_DMb_stat(int i) { return garray___ffloat_DMb_stat[i]; }

void store_global___ffloat_DMb_stat(float a) { global___ffloat_DMb_stat = a; }
void store_garray_pN___ffloat_DMb_stat(float a) { garray___ffloat_DMb_stat[N] = a; }
void store_garray_pI___ffloat_DMb_stat(float a, int i) { garray___ffloat_DMb_stat[i] = a; }


float load_indirect0___ffloat_DMb(float chess_storage(DMb)* p) { return *p; }
float load_indexedp1___ffloat_DMb(float chess_storage(DMb)* p) { return p[ 1]; }
float load_indexedm1___ffloat_DMb(float chess_storage(DMb)* p) { return p[-1]; }
float load_indexedpN___ffloat_DMb(float chess_storage(DMb)* p) { return p[ N]; }
float load_indexedmN___ffloat_DMb(float chess_storage(DMb)* p) { return p[-N]; }
float load_indexedpI___ffloat_DMb(float chess_storage(DMb)* p, int i) { return p[ i]; }
float load_indexedmI___ffloat_DMb(float chess_storage(DMb)* p, int i) { return p[-i]; }

float load_postmodp1___ffloat_DMb(float chess_storage(DMb)*& p) { return *p++; }
float load_postmodm1___ffloat_DMb(float chess_storage(DMb)*& p) { return *p--; }
float load_postmodpN___ffloat_DMb(float chess_storage(DMb)*& p) { float t = *p; p += N; return t; }
float load_postmodmN___ffloat_DMb(float chess_storage(DMb)*& p) { float t = *p; p -= N; return t; }
float load_postmodpI___ffloat_DMb(float chess_storage(DMb)*& p, int i) { float t = *p; p += i; return t; }
float load_postmodmI___ffloat_DMb(float chess_storage(DMb)*& p, int i) { float t = *p; p -= i; return t; }

float load_premod_p1___ffloat_DMb(float chess_storage(DMb)*& p) { return *++p; }
float load_premod_m1___ffloat_DMb(float chess_storage(DMb)*& p) { return *--p; }
float load_premod_pN___ffloat_DMb(float chess_storage(DMb)*& p) { p += N; return *p; }
float load_premod_mN___ffloat_DMb(float chess_storage(DMb)*& p) { p -= N; return *p; }
float load_premod_pI___ffloat_DMb(float chess_storage(DMb)*& p, int i) { p += i; return *p; }
float load_premod_mI___ffloat_DMb(float chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___ffloat_DMb(float a, float chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___ffloat_DMb(float a, float chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___ffloat_DMb(float a, float chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___ffloat_DMb(float a, float chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___ffloat_DMb(float a, float chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___ffloat_DMb(float a, float chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___ffloat_DMb(float a, float chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___ffloat_DMb(float a, float chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___ffloat_DMb(float a, float chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___ffloat_DMb(float a, float chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___ffloat_DMb(float a, float chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___ffloat_DMb(float a, float chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___ffloat_DMb(float a, float chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___ffloat_DMb(float a, float chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___ffloat_DMb(float a, float chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___ffloat_DMb(float a, float chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___ffloat_DMb(float a, float chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___ffloat_DMb(float a, float chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___ffloat_DMb(float a, float chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- double                     // size=8 alignment=4

void pointer_p1___fdouble_DMb(double chess_storage(DMb)*& p) { ++p; }
void pointer_m1___fdouble_DMb(double chess_storage(DMb)*& p) { --p; }
void pointer_pN___fdouble_DMb(double chess_storage(DMb)*& p) { p += N; }
void pointer_mN___fdouble_DMb(double chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___fdouble_DMb(double chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___fdouble_DMb(double chess_storage(DMb)*& p, int i) { p -= i; }

double chess_storage(DMb) global___fdouble_DMb;
double chess_storage(DMb) garray___fdouble_DMb[N+1];

double load_global___fdouble_DMb() { return global___fdouble_DMb; }
double load_garray_pN___fdouble_DMb() { return garray___fdouble_DMb[N]; }
double load_garray_pI___fdouble_DMb(int i) { return garray___fdouble_DMb[i]; }

void store_global___fdouble_DMb(double a) { global___fdouble_DMb = a; }
void store_garray_pN___fdouble_DMb(double a) { garray___fdouble_DMb[N] = a; }
void store_garray_pI___fdouble_DMb(double a, int i) { garray___fdouble_DMb[i] = a; }

double chess_storage(DMb_stat) global___fdouble_DMb_stat;
double chess_storage(DMb_stat) garray___fdouble_DMb_stat[N+1];

double load_global___fdouble_DMb_stat() { return global___fdouble_DMb_stat; }
double load_garray_pN___fdouble_DMb_stat() { return garray___fdouble_DMb_stat[N]; }
double load_garray_pI___fdouble_DMb_stat(int i) { return garray___fdouble_DMb_stat[i]; }

void store_global___fdouble_DMb_stat(double a) { global___fdouble_DMb_stat = a; }
void store_garray_pN___fdouble_DMb_stat(double a) { garray___fdouble_DMb_stat[N] = a; }
void store_garray_pI___fdouble_DMb_stat(double a, int i) { garray___fdouble_DMb_stat[i] = a; }


double load_indirect0___fdouble_DMb(double chess_storage(DMb)* p) { return *p; }
double load_indexedp1___fdouble_DMb(double chess_storage(DMb)* p) { return p[ 1]; }
double load_indexedm1___fdouble_DMb(double chess_storage(DMb)* p) { return p[-1]; }
double load_indexedpN___fdouble_DMb(double chess_storage(DMb)* p) { return p[ N]; }
double load_indexedmN___fdouble_DMb(double chess_storage(DMb)* p) { return p[-N]; }
double load_indexedpI___fdouble_DMb(double chess_storage(DMb)* p, int i) { return p[ i]; }
double load_indexedmI___fdouble_DMb(double chess_storage(DMb)* p, int i) { return p[-i]; }

double load_postmodp1___fdouble_DMb(double chess_storage(DMb)*& p) { return *p++; }
double load_postmodm1___fdouble_DMb(double chess_storage(DMb)*& p) { return *p--; }
double load_postmodpN___fdouble_DMb(double chess_storage(DMb)*& p) { double t = *p; p += N; return t; }
double load_postmodmN___fdouble_DMb(double chess_storage(DMb)*& p) { double t = *p; p -= N; return t; }
double load_postmodpI___fdouble_DMb(double chess_storage(DMb)*& p, int i) { double t = *p; p += i; return t; }
double load_postmodmI___fdouble_DMb(double chess_storage(DMb)*& p, int i) { double t = *p; p -= i; return t; }

double load_premod_p1___fdouble_DMb(double chess_storage(DMb)*& p) { return *++p; }
double load_premod_m1___fdouble_DMb(double chess_storage(DMb)*& p) { return *--p; }
double load_premod_pN___fdouble_DMb(double chess_storage(DMb)*& p) { p += N; return *p; }
double load_premod_mN___fdouble_DMb(double chess_storage(DMb)*& p) { p -= N; return *p; }
double load_premod_pI___fdouble_DMb(double chess_storage(DMb)*& p, int i) { p += i; return *p; }
double load_premod_mI___fdouble_DMb(double chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___fdouble_DMb(double a, double chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___fdouble_DMb(double a, double chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___fdouble_DMb(double a, double chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___fdouble_DMb(double a, double chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___fdouble_DMb(double a, double chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___fdouble_DMb(double a, double chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___fdouble_DMb(double a, double chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___fdouble_DMb(double a, double chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___fdouble_DMb(double a, double chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___fdouble_DMb(double a, double chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___fdouble_DMb(double a, double chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___fdouble_DMb(double a, double chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___fdouble_DMb(double a, double chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___fdouble_DMb(double a, double chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___fdouble_DMb(double a, double chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___fdouble_DMb(double a, double chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___fdouble_DMb(double a, double chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___fdouble_DMb(double a, double chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___fdouble_DMb(double a, double chess_storage(DMb)*& p, int i) { p -= i; *p = a; }

//-- void *                     // size=4 alignment=4

void pointer_p1___Pvoid_DMb(void * chess_storage(DMb)*& p) { ++p; }
void pointer_m1___Pvoid_DMb(void * chess_storage(DMb)*& p) { --p; }
void pointer_pN___Pvoid_DMb(void * chess_storage(DMb)*& p) { p += N; }
void pointer_mN___Pvoid_DMb(void * chess_storage(DMb)*& p) { p -= N; }
void pointer_pI___Pvoid_DMb(void * chess_storage(DMb)*& p, int i) { p += i; }
void pointer_mI___Pvoid_DMb(void * chess_storage(DMb)*& p, int i) { p -= i; }

void * chess_storage(DMb) global___Pvoid_DMb;
void * chess_storage(DMb) garray___Pvoid_DMb[N+1];

void * load_global___Pvoid_DMb() { return global___Pvoid_DMb; }
void * load_garray_pN___Pvoid_DMb() { return garray___Pvoid_DMb[N]; }
void * load_garray_pI___Pvoid_DMb(int i) { return garray___Pvoid_DMb[i]; }

void store_global___Pvoid_DMb(void * a) { global___Pvoid_DMb = a; }
void store_garray_pN___Pvoid_DMb(void * a) { garray___Pvoid_DMb[N] = a; }
void store_garray_pI___Pvoid_DMb(void * a, int i) { garray___Pvoid_DMb[i] = a; }

void * chess_storage(DMb_stat) global___Pvoid_DMb_stat;
void * chess_storage(DMb_stat) garray___Pvoid_DMb_stat[N+1];

void * load_global___Pvoid_DMb_stat() { return global___Pvoid_DMb_stat; }
void * load_garray_pN___Pvoid_DMb_stat() { return garray___Pvoid_DMb_stat[N]; }
void * load_garray_pI___Pvoid_DMb_stat(int i) { return garray___Pvoid_DMb_stat[i]; }

void store_global___Pvoid_DMb_stat(void * a) { global___Pvoid_DMb_stat = a; }
void store_garray_pN___Pvoid_DMb_stat(void * a) { garray___Pvoid_DMb_stat[N] = a; }
void store_garray_pI___Pvoid_DMb_stat(void * a, int i) { garray___Pvoid_DMb_stat[i] = a; }


void * load_indirect0___Pvoid_DMb(void * chess_storage(DMb)* p) { return *p; }
void * load_indexedp1___Pvoid_DMb(void * chess_storage(DMb)* p) { return p[ 1]; }
void * load_indexedm1___Pvoid_DMb(void * chess_storage(DMb)* p) { return p[-1]; }
void * load_indexedpN___Pvoid_DMb(void * chess_storage(DMb)* p) { return p[ N]; }
void * load_indexedmN___Pvoid_DMb(void * chess_storage(DMb)* p) { return p[-N]; }
void * load_indexedpI___Pvoid_DMb(void * chess_storage(DMb)* p, int i) { return p[ i]; }
void * load_indexedmI___Pvoid_DMb(void * chess_storage(DMb)* p, int i) { return p[-i]; }

void * load_postmodp1___Pvoid_DMb(void * chess_storage(DMb)*& p) { return *p++; }
void * load_postmodm1___Pvoid_DMb(void * chess_storage(DMb)*& p) { return *p--; }
void * load_postmodpN___Pvoid_DMb(void * chess_storage(DMb)*& p) { void * t = *p; p += N; return t; }
void * load_postmodmN___Pvoid_DMb(void * chess_storage(DMb)*& p) { void * t = *p; p -= N; return t; }
void * load_postmodpI___Pvoid_DMb(void * chess_storage(DMb)*& p, int i) { void * t = *p; p += i; return t; }
void * load_postmodmI___Pvoid_DMb(void * chess_storage(DMb)*& p, int i) { void * t = *p; p -= i; return t; }

void * load_premod_p1___Pvoid_DMb(void * chess_storage(DMb)*& p) { return *++p; }
void * load_premod_m1___Pvoid_DMb(void * chess_storage(DMb)*& p) { return *--p; }
void * load_premod_pN___Pvoid_DMb(void * chess_storage(DMb)*& p) { p += N; return *p; }
void * load_premod_mN___Pvoid_DMb(void * chess_storage(DMb)*& p) { p -= N; return *p; }
void * load_premod_pI___Pvoid_DMb(void * chess_storage(DMb)*& p, int i) { p += i; return *p; }
void * load_premod_mI___Pvoid_DMb(void * chess_storage(DMb)*& p, int i) { p -= i; return *p; }

void store_indirect0___Pvoid_DMb(void * a, void * chess_storage(DMb)* p) { *p = a; }
void store_indexedp1___Pvoid_DMb(void * a, void * chess_storage(DMb)* p) { p[ 1] = a; }
void store_indexedm1___Pvoid_DMb(void * a, void * chess_storage(DMb)* p) { p[-1] = a; }
void store_indexedpN___Pvoid_DMb(void * a, void * chess_storage(DMb)* p) { p[ N] = a; }
void store_indexedmN___Pvoid_DMb(void * a, void * chess_storage(DMb)* p) { p[-N] = a; }
void store_indexedpI___Pvoid_DMb(void * a, void * chess_storage(DMb)* p, int i) { p[ i] = a; }
void store_indexedmI___Pvoid_DMb(void * a, void * chess_storage(DMb)* p, int i) { p[-i] = a; }

void store_postmodp1___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { *p++ = a; }
void store_postmodm1___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { *p-- = a; }
void store_postmodpN___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { *p = a; p += N; }
void store_postmodmN___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { *p = a; p -= N; }
void store_postmodpI___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p, int i) { *p = a; p += i; }
void store_postmodmI___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p, int i) { *p = a; p -= i; }

void store_premod_p1___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { *++p = a; }
void store_premod_m1___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { *--p = a; }
void store_premod_pN___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { p += N; *p = a; }
void store_premod_mN___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p) { p -= N; *p = a; }
void store_premod_pI___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p, int i) { p += i; *p = a; }
void store_premod_mI___Pvoid_DMb(void * a, void * chess_storage(DMb)*& p, int i) { p -= i; *p = a; }


} //extern "C"  (616 functions)
