
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: memory_PMb.c
// Test memory PMb pointer arithmetic stand-alone and with load/store

//!! no load/store instructions found

#ifndef N // arbitrary value, adapt at will
#define N 7
#endif

extern "C" {

//-- signed char                // size=1 alignment=1

void pointer_p1___schar_PMb(signed char chess_storage(PMb)*& p) { ++p; }
void pointer_m1___schar_PMb(signed char chess_storage(PMb)*& p) { --p; }
void pointer_pN___schar_PMb(signed char chess_storage(PMb)*& p) { p += N; }
void pointer_mN___schar_PMb(signed char chess_storage(PMb)*& p) { p -= N; }
void pointer_pI___schar_PMb(signed char chess_storage(PMb)*& p, int i) { p += i; }
void pointer_mI___schar_PMb(signed char chess_storage(PMb)*& p, int i) { p -= i; }

signed char chess_storage(PMb) global___schar_PMb;
signed char chess_storage(PMb) garray___schar_PMb[N+1];

//!signed char load_global___schar_PMb() { return global___schar_PMb; }
//!signed char load_garray_pN___schar_PMb() { return garray___schar_PMb[N]; }
//!signed char load_garray_pI___schar_PMb(int i) { return garray___schar_PMb[i]; }

//!void store_global___schar_PMb(signed char a) { global___schar_PMb = a; }
//!void store_garray_pN___schar_PMb(signed char a) { garray___schar_PMb[N] = a; }
//!void store_garray_pI___schar_PMb(signed char a, int i) { garray___schar_PMb[i] = a; }


//!signed char load_indirect0___schar_PMb(signed char chess_storage(PMb)* p) { return *p; }
//!signed char load_indexedp1___schar_PMb(signed char chess_storage(PMb)* p) { return p[ 1]; }
//!signed char load_indexedm1___schar_PMb(signed char chess_storage(PMb)* p) { return p[-1]; }
//!signed char load_indexedpN___schar_PMb(signed char chess_storage(PMb)* p) { return p[ N]; }
//!signed char load_indexedmN___schar_PMb(signed char chess_storage(PMb)* p) { return p[-N]; }
//!signed char load_indexedpI___schar_PMb(signed char chess_storage(PMb)* p, int i) { return p[ i]; }
//!signed char load_indexedmI___schar_PMb(signed char chess_storage(PMb)* p, int i) { return p[-i]; }

//!signed char load_postmodp1___schar_PMb(signed char chess_storage(PMb)*& p) { return *p++; }
//!signed char load_postmodm1___schar_PMb(signed char chess_storage(PMb)*& p) { return *p--; }
//!signed char load_postmodpN___schar_PMb(signed char chess_storage(PMb)*& p) { signed char t = *p; p += N; return t; }
//!signed char load_postmodmN___schar_PMb(signed char chess_storage(PMb)*& p) { signed char t = *p; p -= N; return t; }
//!signed char load_postmodpI___schar_PMb(signed char chess_storage(PMb)*& p, int i) { signed char t = *p; p += i; return t; }
//!signed char load_postmodmI___schar_PMb(signed char chess_storage(PMb)*& p, int i) { signed char t = *p; p -= i; return t; }

//!signed char load_premod_p1___schar_PMb(signed char chess_storage(PMb)*& p) { return *++p; }
//!signed char load_premod_m1___schar_PMb(signed char chess_storage(PMb)*& p) { return *--p; }
//!signed char load_premod_pN___schar_PMb(signed char chess_storage(PMb)*& p) { p += N; return *p; }
//!signed char load_premod_mN___schar_PMb(signed char chess_storage(PMb)*& p) { p -= N; return *p; }
//!signed char load_premod_pI___schar_PMb(signed char chess_storage(PMb)*& p, int i) { p += i; return *p; }
//!signed char load_premod_mI___schar_PMb(signed char chess_storage(PMb)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___schar_PMb(signed char a, signed char chess_storage(PMb)* p) { *p = a; }
//!void store_indexedp1___schar_PMb(signed char a, signed char chess_storage(PMb)* p) { p[ 1] = a; }
//!void store_indexedm1___schar_PMb(signed char a, signed char chess_storage(PMb)* p) { p[-1] = a; }
//!void store_indexedpN___schar_PMb(signed char a, signed char chess_storage(PMb)* p) { p[ N] = a; }
//!void store_indexedmN___schar_PMb(signed char a, signed char chess_storage(PMb)* p) { p[-N] = a; }
//!void store_indexedpI___schar_PMb(signed char a, signed char chess_storage(PMb)* p, int i) { p[ i] = a; }
//!void store_indexedmI___schar_PMb(signed char a, signed char chess_storage(PMb)* p, int i) { p[-i] = a; }

//!void store_postmodp1___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { *p++ = a; }
//!void store_postmodm1___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { *p-- = a; }
//!void store_postmodpN___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { *p = a; p += N; }
//!void store_postmodmN___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { *p = a; p -= N; }
//!void store_postmodpI___schar_PMb(signed char a, signed char chess_storage(PMb)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___schar_PMb(signed char a, signed char chess_storage(PMb)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { *++p = a; }
//!void store_premod_m1___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { *--p = a; }
//!void store_premod_pN___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { p += N; *p = a; }
//!void store_premod_mN___schar_PMb(signed char a, signed char chess_storage(PMb)*& p) { p -= N; *p = a; }
//!void store_premod_pI___schar_PMb(signed char a, signed char chess_storage(PMb)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___schar_PMb(signed char a, signed char chess_storage(PMb)*& p, int i) { p -= i; *p = a; }

//-- unsigned char              // size=1 alignment=1

void pointer_p1___uchar_PMb(unsigned char chess_storage(PMb)*& p) { ++p; }
void pointer_m1___uchar_PMb(unsigned char chess_storage(PMb)*& p) { --p; }
void pointer_pN___uchar_PMb(unsigned char chess_storage(PMb)*& p) { p += N; }
void pointer_mN___uchar_PMb(unsigned char chess_storage(PMb)*& p) { p -= N; }
void pointer_pI___uchar_PMb(unsigned char chess_storage(PMb)*& p, int i) { p += i; }
void pointer_mI___uchar_PMb(unsigned char chess_storage(PMb)*& p, int i) { p -= i; }

unsigned char chess_storage(PMb) global___uchar_PMb;
unsigned char chess_storage(PMb) garray___uchar_PMb[N+1];

//!unsigned char load_global___uchar_PMb() { return global___uchar_PMb; }
//!unsigned char load_garray_pN___uchar_PMb() { return garray___uchar_PMb[N]; }
//!unsigned char load_garray_pI___uchar_PMb(int i) { return garray___uchar_PMb[i]; }

//!void store_global___uchar_PMb(unsigned char a) { global___uchar_PMb = a; }
//!void store_garray_pN___uchar_PMb(unsigned char a) { garray___uchar_PMb[N] = a; }
//!void store_garray_pI___uchar_PMb(unsigned char a, int i) { garray___uchar_PMb[i] = a; }


//!unsigned char load_indirect0___uchar_PMb(unsigned char chess_storage(PMb)* p) { return *p; }
//!unsigned char load_indexedp1___uchar_PMb(unsigned char chess_storage(PMb)* p) { return p[ 1]; }
//!unsigned char load_indexedm1___uchar_PMb(unsigned char chess_storage(PMb)* p) { return p[-1]; }
//!unsigned char load_indexedpN___uchar_PMb(unsigned char chess_storage(PMb)* p) { return p[ N]; }
//!unsigned char load_indexedmN___uchar_PMb(unsigned char chess_storage(PMb)* p) { return p[-N]; }
//!unsigned char load_indexedpI___uchar_PMb(unsigned char chess_storage(PMb)* p, int i) { return p[ i]; }
//!unsigned char load_indexedmI___uchar_PMb(unsigned char chess_storage(PMb)* p, int i) { return p[-i]; }

//!unsigned char load_postmodp1___uchar_PMb(unsigned char chess_storage(PMb)*& p) { return *p++; }
//!unsigned char load_postmodm1___uchar_PMb(unsigned char chess_storage(PMb)*& p) { return *p--; }
//!unsigned char load_postmodpN___uchar_PMb(unsigned char chess_storage(PMb)*& p) { unsigned char t = *p; p += N; return t; }
//!unsigned char load_postmodmN___uchar_PMb(unsigned char chess_storage(PMb)*& p) { unsigned char t = *p; p -= N; return t; }
//!unsigned char load_postmodpI___uchar_PMb(unsigned char chess_storage(PMb)*& p, int i) { unsigned char t = *p; p += i; return t; }
//!unsigned char load_postmodmI___uchar_PMb(unsigned char chess_storage(PMb)*& p, int i) { unsigned char t = *p; p -= i; return t; }

//!unsigned char load_premod_p1___uchar_PMb(unsigned char chess_storage(PMb)*& p) { return *++p; }
//!unsigned char load_premod_m1___uchar_PMb(unsigned char chess_storage(PMb)*& p) { return *--p; }
//!unsigned char load_premod_pN___uchar_PMb(unsigned char chess_storage(PMb)*& p) { p += N; return *p; }
//!unsigned char load_premod_mN___uchar_PMb(unsigned char chess_storage(PMb)*& p) { p -= N; return *p; }
//!unsigned char load_premod_pI___uchar_PMb(unsigned char chess_storage(PMb)*& p, int i) { p += i; return *p; }
//!unsigned char load_premod_mI___uchar_PMb(unsigned char chess_storage(PMb)*& p, int i) { p -= i; return *p; }

//!void store_indirect0___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p) { *p = a; }
//!void store_indexedp1___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p) { p[ 1] = a; }
//!void store_indexedm1___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p) { p[-1] = a; }
//!void store_indexedpN___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p) { p[ N] = a; }
//!void store_indexedmN___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p) { p[-N] = a; }
//!void store_indexedpI___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p, int i) { p[ i] = a; }
//!void store_indexedmI___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)* p, int i) { p[-i] = a; }

//!void store_postmodp1___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { *p++ = a; }
//!void store_postmodm1___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { *p-- = a; }
//!void store_postmodpN___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { *p = a; p += N; }
//!void store_postmodmN___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { *p = a; p -= N; }
//!void store_postmodpI___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p, int i) { *p = a; p += i; }
//!void store_postmodmI___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p, int i) { *p = a; p -= i; }

//!void store_premod_p1___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { *++p = a; }
//!void store_premod_m1___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { *--p = a; }
//!void store_premod_pN___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { p += N; *p = a; }
//!void store_premod_mN___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p) { p -= N; *p = a; }
//!void store_premod_pI___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p, int i) { p += i; *p = a; }
//!void store_premod_mI___uchar_PMb(unsigned char a, unsigned char chess_storage(PMb)*& p, int i) { p -= i; *p = a; }

//!! short

//!! unsigned short

//!! int

//!! unsigned

//!! long long

//!! unsigned long long

//!! float

//!! double

//!! void *


} //extern "C"  (100 functions of which 88 skipped)
