
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: register_moves.c
// Test register moves
// (Output is written as an in-out reference, so that it cannot be overlayed with the input)

//! Connection analysis may reveal that certain moves are not available, and those tests are skipped.
//! Note that the connection may be direct or indirect.
//! However, indirect connections via spill memory are not considered at this time!

extern "C" {

//-- signed char

void move___schar_R_R(signed char& chess_storage(R) r, signed char chess_storage(R) a) { r = a; }

//-- unsigned char

void move___uchar_R_R(unsigned char& chess_storage(R) r, unsigned char chess_storage(R) a) { r = a; }

//-- short

void move___sshort_R_R(short& chess_storage(R) r, short chess_storage(R) a) { r = a; }

//-- unsigned short

void move___ushort_R_R(unsigned short& chess_storage(R) r, unsigned short chess_storage(R) a) { r = a; }

//-- int

void move___sint_R_R(int& chess_storage(R) r, int chess_storage(R) a) { r = a; }

//-- unsigned

void move___uint_R_R(unsigned& chess_storage(R) r, unsigned chess_storage(R) a) { r = a; }

//-- long long

//-- unsigned long long

//-- float

void move___ffloat_R_R(float& chess_storage(R) r, float chess_storage(R) a) { r = a; }

//-- double

//-- void *

void move___Pvoid_R_R(void *& chess_storage(R) r, void * chess_storage(R) a) { r = a; }


} //extern "C"  (8 functions)
