
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: simple_function.c
// Test empty function (return only) and simple function call (without arguments)
// (requires spilling of the link register)

extern "C" {

void empty_function() { }

void simple_function_call()
{
    empty_function();  // nested call
    empty_function();  // tail call (may be replaced by jump)
}

void indirect_function_call(void (*fnptr)())
{
    fnptr();  // nested call
    fnptr();  // tail call (may be replaced by indirect jump)
}


} //extern "C"  (3 functions)
