
// File generated by noodle version Q-2020.03#7e5ed72dc8#200717, Wed Mar 22 14:16:27 2023
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// noodle -Pc -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 +NOrlt -D__chess__ -D__programmers_view__ dlx

// File: standalone_intrinsics.c
// Test standalone intrinsics  (in global namespace)
// (Outputs that cannot be returned as function parameters are discarded)

extern "C" {

int intrc_bool_land_bool_bool(int a0, int a1)
    { return land(a0, a1); }

int intrc_bool_lor_bool_bool(int a0, int a1)
    { return lor(a0, a1); }

int intrc_bool_lxor_bool_bool(int a0, int a1)
    { return lxor(a0, a1); }

int intrc_bool_nez___sint(int a0)
    { return nez(a0); }

int intrc_bool_eqz___sint(int a0)
    { return eqz(a0); }

int intrc_bool_nez___uint(unsigned a0)
    { return nez(a0); }

int intrc_bool_eqz___uint(unsigned a0)
    { return eqz(a0); }

int intrc_bool_nez___Pvoid(void * a0)
    { return nez(a0); }

int intrc_bool_eqz___Pvoid(void * a0)
    { return eqz(a0); }

void intrc_void_udiv___uint___uint___uint___uint(unsigned a0, unsigned a1, unsigned & a2, unsigned & a3)
    { udiv(a0, a1, a2, a3); }

void intrc_void_sdiv___sint___sint___sint___sint(int a0, int a1, int & a2, int & a3)
    { sdiv(a0, a1, a2, a3); }

int intrc___sint_clb___sint(int a0)
    { return clb(a0); }

unsigned intrc___uint_clb___uint(unsigned a0)
    { return clb(a0); }

long long intrc___slonglong_div_remainder___slonglong___slonglong___slonglong(long long a0, long long a1, long long & a2)
    { return div_remainder(a0, a1, a2); }

unsigned long long intrc___ulonglong_div_remainder___ulonglong___ulonglong___ulonglong(unsigned long long a0, unsigned long long a1, unsigned long long & a2)
    { return div_remainder(a0, a1, a2); }

int intrc___sint_clb___slonglong(long long a0)
    { return clb(a0); }

int intrc___sint_clb___ulonglong(unsigned long long a0)
    { return clb(a0); }

void intrc_void_char_memory_copy___P__cchar___P__cchar___sint(volatile char * a0, const volatile char * a1, const int a2)
    { char_memory_copy(a0, a1, a2); }

void intrc_void_short_memory_copy___P__sshort___P__sshort___sint(volatile short * a0, const volatile short * a1, const int a2)
    { short_memory_copy(a0, a1, a2); }

void intrc_void_int_memory_copy___P__sint___P__sint___sint(volatile int * a0, const volatile int * a1, const int a2)
    { int_memory_copy(a0, a1, a2); }

void intrc_void_float_raise___sint(int a0)
    { float_raise(a0); }

int intrc___sint_float32_is_signaling_nan___uint(float32 a0)
    { return float32_is_signaling_nan(a0); }

int intrc___sint_float64_is_signaling_nan_dint(float64 a0)
    { return float64_is_signaling_nan(a0); }

int intrc___sint_f32_to_i32___uint(float32 a0)
    { return f32_to_i32(a0); }

float32 intrc___uint_i32_to_f32___sint(int a0)
    { return i32_to_f32(a0); }

float32 intrc___uint_f32_add___uint___uint(float32 a0, float32 a1)
    { return f32_add(a0, a1); }

float32 intrc___uint_f32_sub___uint___uint(float32 a0, float32 a1)
    { return f32_sub(a0, a1); }

float32 intrc___uint_f32_mul___uint___uint(float32 a0, float32 a1)
    { return f32_mul(a0, a1); }

float32 intrc___uint_f32_div___uint___uint(float32 a0, float32 a1)
    { return f32_div(a0, a1); }

float32 intrc___uint_f32_neg___uint(float32 a0)
    { return f32_neg(a0); }

int intrc_bool_f32_le___uint___uint(float32 a0, float32 a1)
    { return f32_le(a0, a1); }

int intrc_bool_f32_lt___uint___uint(float32 a0, float32 a1)
    { return f32_lt(a0, a1); }

int intrc_bool_f32_eq___uint___uint(float32 a0, float32 a1)
    { return f32_eq(a0, a1); }

int intrc___sint_f64_to_i32_dint(float64 a0)
    { return f64_to_i32(a0); }

float64 intrc_dint_i32_to_f64___sint(int a0)
    { return i32_to_f64(a0); }

float64 intrc_dint_f32_to_f64___uint(float32 a0)
    { return f32_to_f64(a0); }

float32 intrc___uint_f64_to_f32_dint(float64 a0)
    { return f64_to_f32(a0); }

float64 intrc_dint_f64_add_dint_dint(float64 a0, float64 a1)
    { return f64_add(a0, a1); }

float64 intrc_dint_f64_sub_dint_dint(float64 a0, float64 a1)
    { return f64_sub(a0, a1); }

float64 intrc_dint_f64_mul_dint_dint(float64 a0, float64 a1)
    { return f64_mul(a0, a1); }

float64 intrc_dint_f64_div_dint_dint(float64 a0, float64 a1)
    { return f64_div(a0, a1); }

float64 intrc_dint_f64_neg_dint(float64 a0)
    { return f64_neg(a0); }

int intrc_bool_f64_le_dint_dint(float64 a0, float64 a1)
    { return f64_le(a0, a1); }

int intrc_bool_f64_lt_dint_dint(float64 a0, float64 a1)
    { return f64_lt(a0, a1); }

int intrc_bool_f64_eq_dint_dint(float64 a0, float64 a1)
    { return f64_eq(a0, a1); }


} //extern "C"  (45 functions)
