
L = ../lib
P = plx
GO_DIR = ../hdl/$(P)_vlog

all : pdc_register_moves.c pdc_opcodes.h

pdc_register_moves.c: pdc_register_moves.dis ins2c.perl
	perl ins2c.perl < $< > $@

pdc_register_moves.dis: pdc_register_moves.x
	darts -d -L +Ihex -I $(L) -o $@ $< $(P)

pdc_register_moves.x: pdc_register_moves.s
	darts -E -I $(L) -o $@ $< $(P)

pdc_opcodes.h: $(GO_DIR)/pdc_opcodes.h
	cp $(GO_DIR)/pdc_opcodes.h .

clean:
	rm -f pdc_register_moves.c pdc_register_moves.dis pdc_register_moves.x
