
// File generated by pdg version Q-2020.03#7e5ed72dc8#200717
// Copyright 2014-2020 Synopsys, Inc. All rights reserved.
// pdg -P -Iisg +wisg -Iruntime/include -DCHESS_CXX_ATTRIBUTES -D__tct_patch__=300 -D__checkers__ dlx

#include "dlx_inline_primitives.h"
#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wparentheses"
#endif

namespace dlx_primitive {

} // namespace dlx_primitive
