#!/bin/sh -e

chessmk lib/blx.prx -r
chessmk lib/blx.prx
chessmk -C Native       lib/libnative.prx
chessmk -C Release      lib/libblx.prx
chessmk -C Debug        lib/libblx.prx
chessmk -C Release_LLVM lib/compiler-rt/compiler_rt.prx
chessmk -C Debug_LLVM   lib/compiler-rt/compiler_rt.prx
chessmk -C Release      lib/runtime/libc.prx
chessmk -C Release_LLVM lib/runtime/libc.prx
chessmk -C Debug        lib/runtime/libc.prx
chessmk -C Debug_LLVM   lib/runtime/libc.prx
chessmk -C Release      lib/runtime/libm.prx
chessmk -C Release_LLVM lib/runtime/libm.prx
chessmk -C Debug        lib/runtime/libm.prx
chessmk -C Debug_LLVM   lib/runtime/libm.prx
chessmk -C Release      lib/softfloat/softfloat.prx
chessmk -C Debug        lib/softfloat/softfloat.prx
chessmk iss/blx_ca.prx

