
// File generated by checkers version P-2019.09#3993eff943#190321
// Copyright 2014-2021 Synopsys, Inc. All rights reserved.
// checkers -B -v -M -cwork/tlx_sc_dbg/LNa64/tlx_sc_dbg.ccf tlx

// Processor: tlx

#include <tlm.h>
#include <scml2.h>
#include <systemc>

#include "Mdl_tlx_systemc.h"
#include "checkers_sc_time_gater.h"



template <typename DT, unsigned bits>
SC_MODULE(Tlm2Memory)
{
public:
  tlm::tlm_target_socket<bits> socket;

public:
  SC_HAS_PROCESS(Tlm2Memory);

  Tlm2Memory(sc_core::sc_module_name name, unsigned mem_size)
    : sc_core::sc_module(name)
    , socket    ("socket")
    , mAdapter  ("mAdapter", socket)
    , mMemory   ("mMemory", mem_size)
  {
    mAdapter(mMemory);
  }

private:
  scml2::tlm2_gp_target_adapter<bits> mAdapter;
  scml2::memory<DT>                   mMemory;
};


#define PM_SIZE (1ULL<<18) /* in words  */
#define DM_SIZE (1ULL<<24) /* in byte */



SC_MODULE(tlx_top_sc)
{
public:
  sc_in_clk                             clock;
  sc_in<bool>                           reset;

  // ------------------------------------------
  // Internal connections
  // ------------------------------------------

  // PM
  Tlm2Memory<unsigned,32>                 pm;

  // DM
  Tlm2Memory<unsigned char,8>             dm;

  // time gater (connection to GUI)
  checkers_time_gater                   gclock;
  sc_signal<bool>                       scbreak_req;

  // TLX core
  tlx_sc                                tlx;

  // ------------------------------------------
  // Constructor
  // ------------------------------------------
public:
  SC_CTOR(tlx_top_sc)
    : clock             ("clock"        )
    , reset             ("reset"        )
    , pm                ("pm", PM_SIZE  )
    , dm                ("dm", DM_SIZE  )
    , tlx("TLX")                                // Core
    , gclock("gclock")                          // time gater (connection to GUI)
  {
    // TLX connections
    tlx.clock           (clock          );
    tlx.reset           (reset          );

    tlx.scbreak_req     (scbreak_req    );

    // TLX - PM
    tlx.p_PM            (pm.socket      );

    // TLX - DM
    tlx.p_DMb           (dm.socket      );

    // time gater (connection to GUI)
    gclock.clock        (clock          );
    gclock.break_req    (scbreak_req    );

  } // c'tor

}; // tlx_top_sc



Tcl_Interp* sc_interp = 0;

int sc_main(int, char*[])
{
  // Top module
  tlx_top_sc tlx_top("tlx_top");

  // signals
  sc_clock                       clock;
  sc_signal<bool>                reset;

  // Connections
  tlx_top.clock                 (clock          );
  tlx_top.reset                 (reset          );

  // Run
  reset = true;
  sc_start(sc_time(100, SC_NS));
  reset = false;
  sc_start();

  return 0;
}

