#!/bin/sh

PROC="dlx"

which chessmk > /dev/null
[ $? -ge 1 ] && exit 1

WORKDIR="`dirname $0`"
echo "workdir: $WORKDIR"

chessmk -r $WORKDIR/model.prx
chessmk -r $WORKDIR/debug_client/${PROC}_client.prx

cd $WORKDIR/regression; ./domake virgin; cd -

cd $WORKDIR/debug_client;           make -f makefile.ins clean; cd -
cd $WORKDIR/debug_client/tests;     make                 clean; cd -

find $WORKDIR -name Release      | xargs rm -rf
find $WORKDIR -name Release_LLVM | xargs rm -rf
find $WORKDIR -name Debug        | xargs rm -rf
find $WORKDIR -name Debug_LLVM   | xargs rm -rf
find $WORKDIR -name Native       | xargs rm -rf
find $WORKDIR -name \*.rpt       | xargs rm -rf
find $WORKDIR -name \*.prxui     | xargs rm -rf
find $WORKDIR -name \*.log       | xargs rm -rf
find $WORKDIR -name \*_work      | xargs rm -rf


/bin/rm -rf lib/*.a
/bin/rm -rf lib/*.o
/bin/rm -rf lib/*.o.lst
/bin/rm -rf lib/isg
/bin/rm -rf lib/chesswork
/bin/rm -rf lib/oneliners
/bin/rm -rf lib/runtime/lib/*.a
/bin/rm -rf lib/runtime/lib/*.o
/bin/rm -rf lib/runtime/lib/*.o.lst
/bin/rm -rf lib/runtime/lib/chesswork
/bin/rm -rf lib/softfloat/lib/*.a
/bin/rm -rf lib/softfloat/lib/*.o
/bin/rm -rf lib/softfloat/lib/*.o.lst
/bin/rm -rf lib/softfloat/lib/chesswork
/bin/rm -rf iss/dlx
/bin/rm -rf iss/dlx_ca.ccf
/bin/rm -rf iss/dlx_ca_work
/bin/rm -rf iss/dlx_ia
/bin/rm -rf iss/dlx_ia.ccf
/bin/rm -rf iss/dlx_ia_work
/bin/rm -rf debug_client/dlx_client
/bin/rm -rf debug_client/dlx_client_work/
/bin/rm -rf debug_client/tests/*.log
/bin/rm -rf debug_client/tests/*.ll
/bin/rm -rf hdl/dlx_vhdl_pdg
/bin/rm -rf hdl/dlx_vhdl_go
/bin/rm -rf hdl/dlx_vlog_pdg
/bin/rm -rf hdl/dlx_vlog_go

# cd regression; ./domake virgin; cd ..

